Repository Automattic/vip-go-mu-plugins, pull requests merged in 2018-04, with the labels that each got.

#518 Add `wpcomvip` to restricted usernames
  security.php
  tests/bootstrap.php
  tests/test-security.php
Labels: [Status] Ready to Deploy

#861 Update error docs
  errors/alloptions-limit.html
  errors/site-maintenance.html
Labels: [Status] Needs Review

#868 Files: Extract Files API communication into new class
  files/class-api-client.php
  files/class-curl-streamer.php
  tests/files/test-api-client.php
  tests/files/test-curl-streamer.php
  tests/fixtures/files/stream.txt
  tests/fixtures/files/upload.jpg
Labels: [Status] Ready to Deploy

#869 Files: WP_Filesystem_VIP
  files/class-api-client.php
  files/class-wp-filesystem-vip-uploads.php
  files/class-wp-filesystem-vip.php
  tests/files/test-api-client.php
  tests/files/test-curl-streamer.php
  tests/files/test-wp-filesystem-vip-uploads.php
  tests/files/test-wp-filesystem-vip.php
Labels: [Status] In Progress
