Repository Automattic/vip-go-mu-plugins, pull requests merged in 2018-12, with the labels that each got.

#1024 Connect akismet during migration cleanup
  vip-helpers/vip-migrations.php
Labels: [Status] Ready to Deploy

#1029 Use mangle cache invalidation for file purges
  a8c-files.php
Labels: [Status] Ready to Deploy

#992 Block wp_mail if VIP_BLOCK_WP_MAIL is set
  vip-mail.php
Labels: [Status] Ready to Deploy

#1039 Modify the 5.0 about page to be more VIP-specific
  gutenberg-ramp.php
Labels: [Status] Needs Review

#1034 Require the GUTENBERG_USE_PLUGIN constant
  vip-helpers/vip-utils.php
Labels: [Status] Needs Review

#1043 Retain < 5.0 behaviour for tinyMCE scripts.
  http-concat.php
Labels: [Status] Needs Review

#1042 Use "display" instead of "load"
  vip-plugins/vip-plugins.php
Labels: [Status] Ready to Merge

#1052 Add conditional loading of streamwrapper
  a8c-files.php
  files/class-vip-filesystem.php
  vip-filesystem.php
Labels: [Status] Ready to Deploy
