Repository Automattic/vip-go-mu-plugins, pull requests merged in 2018-10, with the labels that each got.

#965 Prevent Notice when calling `nocache_headers()` super early
  misc.php
  tests/test-check-for-404-and-remove-cache-headers.php
Labels: [Status] Ready to Merge

#980 Fix hash_equals() php warning
  lib/proxy/ip-forward.php
  tests/test-lib-proxy-ip-forward.php
Labels: [Status] Ready to Deploy

#968 Privacy: Use different hooks for overriding filters
  001-core/privacy.php
Labels: [Status] Needs Review

#956 Enable WP_Filesystem_VIP
  a8c-files.php
  files/init-filesystem.php
Labels: [Status] Ready to Deploy

#975 Updated PHPUnit setup instructions
  README-PUBLIC.md
  README.md
Labels: [Status] Needs Review

#985 Impliment concatention whitelist for Ramp
  gutenberg-ramp.php
Labels: [Status] Ready to Merge

#983 Fix spelling error
  files/class-image-sizes.php
Labels: [Status] Ready to Deploy

#987 WPCOM Compat: 'plugins' means the default plugin location
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#989 Run dbDelta during migration cleanup
  vip-helpers/vip-migrations.php
Labels: [Status] Needs Review

#998 Changed group metric calculation
  stats.php
Labels: [Status] Needs Review
