Repository Automattic/vip-go-mu-plugins, pull requests merged in 2018-05, with the labels that each got.

#889 Added a call to remove the `vaultpress` option from the db prior to plugin registration
  vip-helpers/vip-migrations.php
Labels: [Status] Ready to Merge

#892 Improve Gutenberg Ramp argument consistency
  ramp-for-gutenberg.php
Labels: [Status] Ready to Merge

#895 Add custom handlers for WordPress 4.9.6 personal data export feature
  001-core.php
  001-core/privacy.php
  files/class-api-client.php
Labels: [Status] Needs Review, [Tests] Needs Tests

#896 Privacy Compat Fixes
  001-core/privacy.php
Labels: [Status] In Progress
