Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-04, with the labels that each got.

#1189 Plugin Compat: Add fix for Contact Form 7 attachments
  plugin-fixes.php
Labels: [Status] Needs Review

#1185 Make (Local) Core Upgrades Work Again
  files/class-wp-filesystem-vip.php
Labels: [Status] Needs Review

#1197 Lockout: Fix message display when locked
  security/class-lockout.php
Labels: [Status] Retro Review

#1180 Vary Cache: Add Maintenance Mode Bypass example
  cache/README.md
  cache/examples/segmentation-maintenance-mode-bypass/vip-config.php
Labels: [Status] Needs Review

#1121 Make feed cache create method static
  vip-feed-cache/class-vip-go-feed-cache.php
Labels: [Status] Ready to Merge

#1212 Adds missing image sizes to attachment metadata
  a8c-files.php
Labels: [Status] Ready to Deploy

#1216 Cache a local copy of generated image sizes
  a8c-files.php
Labels: [Status] Needs Review

#1217 Prevent warnings when sizes key not set
  a8c-files.php
Labels: [Status] Deployed

#1206 Prevent modifications of the VIP machine user
  bin/phpunit-docker.sh
  security.php
  security/machine-user.php
  tests/security/test-machine-user.php
Labels: [Status] Ready to Deploy

#1200 Move update filesizes job
  a8c-files.php
  files/class-meta-updater.php
  files/class-vip-filesystem.php
Labels: [Status] Ready to Deploy

#1218 Fix PHP Warning
  a8c-files.php
Labels: [Status] Needs Review

#1230 Don't force 2FA for OneLogin or SimplSaml
  two-factor.php
Labels: [Status] Needs Review

#1226 Update the Powered By domain to wpvip.com
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy
