Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-07, with the labels that each got.

#1292 Vary cache on Origin
  security.php
Labels: [Status] Needs Review

#1307 Push back 2FA another week
  two-factor.php
Labels: [Status] Deployed

#1301 Add JP debug headers for broken connections
  jetpack.php
  vip-helpers/vip-utils.php
Labels: [Status] Needs Review

#1291 Allow bulk editing for hierarchical post types
  performance/bulk-edit.php
Labels: [Status] Ready to Deploy, [Type] Bug

#1146 Stream Wrappers: Improve exception handling
  files/class-vip-filesystem-stream-wrapper.php
Labels: [Status] Ready to Merge

#1310 Two Factor: Add `wpcom_vip_is_two_factor_forced` before default to allow overriding
  two-factor.php
Labels: [Status] Deployed

#1311 2FA: Don't restrict wpcomvip, logins are blocked anyway
  000-vip-init.php
  two-factor.php
Labels: [Status] Needs Review
