Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-06, with the labels that each got.

#1277 Add phone verification step when configuring SMS two-factor
  wpcom-vip-two-factor/sms-provider.php
Labels: [Status] Needs Review

#1286 Update templates to include public repo warning
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#880 Fix WPCOM_VIP_PRIVATE_DIR
  000-vip-init.php
Labels: [Impact] High, [Status] Ready to Merge

#1285 Cache Personalization: Tweaks to encrypted segmentation flow
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Ready to Merge
