Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-05, with the labels that each got.

#1231 Don't show 2fa notice on Edit Post screen
  two-factor.php
Labels: [Status] Retro Review

#1228 Updates files service to allow split URL setup, and go-vip.net domain
  a8c-files.php
  tests/test-a8c-files-utils.php
Labels: [Status] Ready to Deploy

#1234 Add wpcom_vip_enable_two_factor filter
  two-factor.php
Labels: [Status] Ready to Deploy

#1237 Add wpcom_vip_two_factor_enforcement_cap filter
  two-factor.php
Labels: [Status] Ready to Deploy

#1235 Better screen check
  two-factor.php
Labels: [Status] Ready to Deploy

#1238 Don't force 2FA for Jetpack SSO users that have Two-step enabled
  two-factor.php
  wpcom-vip-two-factor/is-jetpack-sso.php
Labels: [Status] Ready to Merge

#1236 Added footnote to SMS provider field about country codes
  wpcom-vip-two-factor/sms-provider.php
Labels: [Status] Ready to Deploy

#1240 Two Factor: Load MS constants
  wpcom-vip-two-factor/is-jetpack-sso.php
Labels: [Status] Needs Review, [Status] Retro Review

#1245 Only lock out contributors and up
  security/class-lockout.php
Labels: [Status] Needs Review

#1247 Enforce captcha for email sending (fix priority)
  vip-jetpack/vip-jetpack.php
Labels: [Pri] High, [Status] Needs Review, [Type] Bug

#1249 Fix reported JP version (7.3)
  jetpack.php
Labels: [Status] Ready to Deploy

#1260 Prevent super admin updates when locked
  security/class-lockout.php
  tests/security/test-lockout.php
Labels: [Status] Needs Review

#1259 Better error handling for Twilio
  lib/sms.php
Labels: [Status] Needs Review

#1256 VaultPress 1.9.10
  vaultpress.php
  vaultpress/cron-tasks.php
  vaultpress/readme.txt
  vaultpress/vaultpress.php
  vaultpress/vp-scanner.php
Labels: [Status] Ready to Deploy

#1254 Akismet 4.1.2
  akismet.php
  akismet/_inc/akismet.css
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet-admin.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/get.php
  akismet/wrapper.php
Labels: [Status] Ready to Deploy

#1233 Update validate-attachments for extra URLs
  wp-cli/vip-migrations.php
Labels: [Status] Needs Review

#1177 Add initial Circle CI config
  .circleci/config.yml
  .travis.yml
  ci/prepare.sh
Labels: [Status] In Progress

#1258 Add `two-factor report` CLI command
  wp-cli/vip-two-factor.php
Labels: [Status] Ready to Deploy

#1264 wp vip two-factor report: Add option to set format
  wp-cli/vip-two-factor.php
Labels: [Status] Needs Review, [Status] Retro Review

#1253 Allow JP Sync to run during WP CLI commands
  vip-jetpack/vip-jetpack.php
Labels: [Pri] High, [Status] Ready to Deploy, [Type] Bug

#1265 Send alloptions alerts to vip-deploy-on-call
  alloptions-limit.php
Labels: [Status] Needs Review

#1267 2FA: Push back enforcement
  two-factor.php
Labels: [Status] Retro Review
