Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-12, with the labels that each got.

#1355 Improve stream wrapper cache memory efficiency
  files/class-api-cache.php
  files/class-api-client.php
  tests/files/test-vip-filesystem-api-cache.php
Labels: [Status] Needs Review

#1369 Remove ‘manage’ as a mandatory JP module
  vip-jetpack/jetpack-mandatory.php
Labels: [Status] Ready to Deploy

#1342 Two Factor: Add wpcom_vip_use_custom_sso filter
  two-factor.php
Labels: [Status] Ready to Deploy

#1322 QM: Fix docs
  query-monitor.php
Labels: [Status] Ready to Deploy, [Type] Bug

#1327 Debug Bar: Play nice with other enable filters
  debug-bar.php
Labels: [Status] Ready to Deploy

#1376 Circle CI: Test on PHP 7.4
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#1384 Add trailing slash to make valid upload path
  files/class-vip-filesystem.php
Labels: [Status] Needs Review

#1377 Allow local install/updates for plugins/themes/language packs via WP-CLI
  files/class-wp-filesystem-vip.php
  tests/files/test-wp-filesystem-vip.php
Labels: [Status] Ready to Deploy

#1374 Add filter for elasticpress index name
  tests/vip-helpers/test-vip-elasticsearch.php
  vip-helpers/vip-elasticsearch.php
Labels: [Status] Ready to Deploy

#1380 Refresh PHPCS configuration
  composer.json
  composer.lock
  phpcs.xml
Labels: [Pri] Low, [Type] Enhancement

#1387 Add default EP_SYNC_CHUNK_LIMIT constant for bulk syncing
  tests/vip-helpers/test-vip-elasticsearch.php
  vip-helpers/vip-elasticsearch.php
Labels: [Status] Ready to Deploy

#1388 Conditionally add blog_id to index name
  tests/vip-helpers/test-vip-elasticsearch.php
  vip-helpers/vip-elasticsearch.php
Labels: [Status] Ready to Deploy
