Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-01, with the labels that each got.

#1057 Update comment for check uniqueness method
  a8c-files.php
Labels: [Status] Ready to Deploy

#1060 Remove unnecessary cache purges on file upload
  vip-cache-manager/vip-cache-manager.php
Labels: [Status] Ready to Deploy

#1061 Add filetype check to Stream Wrappers
  files/class-api-client.php
  files/class-vip-filesystem-stream-wrapper.php
  files/class-vip-filesystem.php
  tests/files/test-api-client.php
  tests/files/test-vip-filesystem.php
Labels: [Status] Ready to Deploy

#1065 Bump up JP_SITEMAP_BATCH_SIZE to 200
  jetpack.php
Labels: [Status] Ready to Deploy

#1068 Add Stream Wrapper purge cache on delete
  files/class-vip-filesystem.php
  tests/files/test-vip-filesystem.php
Labels: [Status] Ready to Deploy

#1076 Fix partner-provision.sh on CLI containers
  jetpack-start/bin/partner-provision.sh
Labels: [Status] Ready to Merge

#1079 Update Filesystem/Stream Wrapper errors
  files/class-vip-filesystem-stream-wrapper.php
  files/class-vip-filesystem.php
Labels: [Status] Ready to Deploy

#1082 Don't track upload/delete stats for imports
  stats.php
Labels: [Status] Needs Review

#1093 Set shorter timeouts for low-cost API calls
  files/class-api-client.php
Labels: [Status] Ready to Deploy

#1083 WP_Filesystem: Switch `uploads` paths to use WP_Filesystem_Direct
  files/class-wp-filesystem-vip.php
Labels: [Status] Ready to Deploy

#1088 Remove unused, deprecated functions
  vip-helpers/vip-deprecated.php
Labels: [Status] Ready to Deploy
