Repository Automattic/vip-go-mu-plugins, pull requests merged in 2019-02, with the labels that each got.

#1098 Add to file cache on get file request
  files/class-api-client.php
Labels: [Status] Ready to Deploy

#1094 Akismet 4.1.1
  akismet.php
  akismet/_inc/akismet.css
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/config.php
  akismet/views/get.php
  akismet/views/notice.php
Labels: [Status] Needs Review

#1101 Add get attached file filter
  files/class-vip-filesystem.php
  tests/files/test-vip-filesystem.php
Labels: [Status] In Progress

#1106 Optimize Stream_Wrapper::stream_open
  files/class-api-client.php
  files/class-vip-filesystem-stream-wrapper.php
  tests/files/test-api-client.php
Labels: [Status] Needs Review

#1107 Fix `wp --skip-plugins`
  vip-helpers/vip-utils.php
  z-client-mu-plugins.php
Labels: [Status] Ready to Merge

#1109 Update VaultPress to 1.9.8
  vaultpress.php
  vaultpress/readme.txt
  vaultpress/vaultpress.php
Labels: [Status] Ready to Deploy

#1111 Disable stream wrapper on AMS
  a8c-files.php
Labels: [Status] Ready to Deploy

#1114 Add debug log for API client
  files/class-api-client.php
Labels: [Status] Ready to Deploy

#1110 Register Stream Wrapper `init` hook earlier
  a8c-files.php
Labels: [Status] Ready to Deploy

#1115 a8c-files: Load Photon on `init`
  a8c-files.php
Labels: [Status] Ready to Merge

#1117 Allow E_USER_NOTICE for debugging in API Client
  files/class-api-client.php
Labels: [Status] Needs Review

#1118 Store the filesize in meta on upload
  files/class-vip-filesystem.php
  tests/files/test-vip-filesystem.php
Labels: [Status] Ready to Deploy

#1092 Add library to implement cache variance
  cache/class-vary-cache.php
Labels: [Status] Ready to Deploy

#1119 Add lockout plugin
  security.php
  security/class-lockout.php
  tests/security/test-lockout.php
Labels: [Status] Needs Review

#1127 Enable Vary Cache with encrypted groups/data
  cache/class-vary-cache.php
Labels: [Status] Ready to Deploy

#1138 Fix group check logic to return false for groups with empty segments
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Ready to Deploy

#1135 Vary Cache: Set group separator to be more unique
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Needs Review

#1144 Vary Cache: Send a debug header if WP_DEBUG enabled
  cache/class-vary-cache.php
Labels: [Status] Ready to Deploy

#1142 Vary Cache: Fix version prefix
  cache/class-vary-cache.php
Labels: [Status] Ready to Merge

#1128 Vary_Cache: Add single version of register_group
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Ready to Merge

#1145 Vary Cache: Validate auth keys and cookie values
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Ready to Deploy

#1143 Vary Cache: Group WP hooks / callbacks together
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Ready to Deploy

#1148 Bump PHPUnit version so that CI tests are consistent with local tests
  composer.json
  composer.lock
Labels: [Status] Ready to Merge

#1151 Vary Cache: Set cookies only once
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Needs Review

#1156 Change set_group_for_user() to check if group is registered first
  cache/class-vary-cache.php
  tests/cache/test-vary-cache.php
Labels: [Status] Ready to Deploy
