Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-04, with the labels that each got.

#1531 Remove fuzziness from EP search queries
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1379 Error page: Use descriptive code for alloptions
  errors/alloptions-limit.html
Labels: [Pri] Low, [Status] Ready to Deploy, [Type] Enhancement

#1527 Add mirrored search requests ability for evaluation
  search/includes/classes/class-search.php
Labels: [Status] Needs Review

#1526 Track Search request metrics
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1535 Added a quick win for search relevancy
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1533 First pass at simple plugin upgrade script
  bin/upgrade-plugin.sh
Labels: [Status] Ready to Deploy

#1532 Akismet 4.1.4
  akismet.php
  akismet/_inc/akismet.css
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet-admin.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/setup.php
Labels: [Status] Ready to Deploy

#1496 Add WP-CLI command to manage option autoload
  wp-cli/class-option-autoload.php
Labels: [Status] Ready to Deploy

#1537 Added new defaults for date relevancy
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1538 Fix TypeError in maybe_wp_debug_log_entries
  logstash/class-logger.php
  tests/logstash/test-logger.php
Labels: [Status] Ready to Deploy

#1543 #1539: Update Vaultpress
  vaultpress/vaultpress.php
Labels: [Status] Ready to Deploy

#1318 2FA: Don't check wpcom_vip_is_two_factor_forced() for machine user
  two-factor.php
Labels: [Status] Ready to Deploy

#1545 Reduced diff output for validate-content and added options
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-health.php
Labels: [Status] Ready to Deploy

#1547 Add inspect flag for validate-contents command
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy

#1546 Add a singleton instance() method to Search class
  000-vip-init.php
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1549 Fixes an issue with `rename()` breaking files.
  files/class-vip-filesystem-stream-wrapper.php
  tests/files/test-vip-filesystem-stream-wrapper.php
Labels: [Status] Needs Review

#1426 Streamwrapper: Upload file to fileservice on fopen
  files/class-api-client.php
  files/class-vip-filesystem-stream-wrapper.php
Labels: [Status] Ready to Deploy

#1553 Streamwrapper: Check if file is read mode first before flush
  files/class-vip-filesystem-stream-wrapper.php
Labels: [Status] Needs Review

#1554 Streamwrapper: Fix bug in file mode validation method
  files/class-vip-filesystem-stream-wrapper.php
  tests/files/test-vip-filesystem-stream-wrapper.php
Labels: [Status] Ready to Deploy

#1536 Index queue system MVP
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  search/includes/classes/commands/class-queuecommand.php
  search/includes/classes/queue/class-schema.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Needs Review

#1551 Offload bulk indexing to queue
  search/includes/classes/class-queue.php
  search/includes/classes/commands/class-queuecommand.php
  search/includes/classes/queue/class-cron.php
  tests/search/includes/classes/queue/test-class-cron.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1559 Offload queries to database if RPS too high in VIP Search
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1561 Set default es shard + replica count
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1562 Disable EP queries on the HP on some sites
  search/includes/classes/class-search.php
Labels: [Status] Needs Review, [Status] Retro Review

#1564 Added whitelist for exact search
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1566 Return the correct view count from wpcom_vip_get_post_pageviews()
  vip-helpers/vip-stats.php
Labels: [Status] Ready to Deploy

#1555 Update WordPress.com VIP to WordPress VIP
  000-vip-init.php
Labels: [Status] Ready to Deploy

#1289 Remove limit from `get_sites`, when running with the `--network` flag.
  jetpack-start/wp-cli-api.php
Labels: [Status] Ready to Deploy

#852 Add doing_it_wrong for late loading plugins
  tests/vip-helpers/test-wpcom-vip-load-plugin.php
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1557 Uploads: Add length check for file name/path
  files/class-vip-filesystem.php
  tests/files/test-vip-filesystem.php
Labels: [Status] Ready to Deploy

#1287 Fixes attachments with completely missing meta
  files/class-meta-updater.php
Labels: [Status] Ready to Deploy

#1304 Clear old_slug cache when a post’s date is changed
  vip-helpers/vip-caching.php
Labels: [Status] Ready to Deploy, [Type] Bug

#1401 Use wp_register_plugin_realpath for improved symlink support [#1400]
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1428 Clean up leftover _encloseme
  lib/class-vip-encloseme-cleanup.php
Labels: [Status] Ready to Deploy

#1560 Added tests for ep_skip_query_integration and edited ep_skip_query_integration from tests/feedback
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1290 Adding features to validate-attachments CSV
  wp-cli/vip-migrations.php
Labels: [Status] Ready to Deploy

#1571 Add deadlock protection to indexing queue
  search/includes/classes/class-queue.php
  search/includes/classes/queue/class-cron.php
  search/includes/classes/queue/class-schema.php
  tests/search/includes/classes/queue/test-class-cron.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1569 Add documents that failed to index to queue
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1574 Add per site/index search stats
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review
