Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-06, with the labels that each got.

#1609 Recommend vip-go-mu-dev for development
  README.md
Labels: [Status] Needs Review

#1608 Increase vip_safe_wp_remote_request timeouts
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1381 wpcom_vip_maybe_skip_old_slug_redirect(): Improve compatibility with local setups
  vip-helpers/vip-caching.php
Labels: [Pri] Low, [Status] Ready to Deploy, [Type] Enhancement

#1610 Increase timeouts for bulk ES operations
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1613 Add basic site privacy
  000-vip-init.php
  config/class-sync.php
  security.php
  security/class-private-sites.php
  tests/security/test-class-private-sites.php
Labels: [Status] Needs Review

#1611 Display 'Not Proxied' flag when not proxied.
  000-debug/0-load.php
  000-debug/not-proxied-flag.php
Labels: [Status] Ready to Deploy

#1615 is_proxied_automattician: Check constant exists
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1614 Akismet 4.1.6
  akismet.php
  akismet/_inc/akismet.css
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet-admin.php
  akismet/readme.txt
Labels: [Status] Ready to Deploy

#1623 Wire up the `_encloseme` meta cleanup class
  000-vip-init.php
Labels: [Status] Ready to Deploy

#1592 Offload term edits to cron
  search/includes/classes/class-queue.php
  search/includes/classes/queue/class-cron.php
Labels: [Status] Ready to Deploy

#1622 Increment stat in statsd when query is ratelimited
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1624 Add queue size stat to statsd after processing a batch
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1628 Update es-wp-query subtree
  search/es-wp-query/adapters/vip-search.php
  search/es-wp-query/class-es-wp-query-wrapper.php
Labels: [Status] Ready to Deploy

#1625 Truncate search strings to a reasonable length
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1627 Alias elasticpress commands to vip-search
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1629 Only mirror tax query if it's also not a search query
  search/includes/classes/class-search.php
Labels: [Status] Needs Review

#1630 Expand list of sites with mirrored tax queries
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1633 Stub Cache class, implement Advanced Post Cache compatibility.
  search/includes/classes/class-cache.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-cache.php
Labels: [Status] Ready to Deploy

#1634 Set proper global states for Automattic\VIP\Search\Cache_Test
  tests/search/includes/classes/test-class-cache.php
Labels: [Status] Deployed

#1632 Enable logs delivery to Elasticsearch debug index for CLI containers
  logstash/class-logger.php
Labels: [Status] Ready to Deploy

#1635 Split the ep_skip_query_integration filter into a reusable function
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1603 Add allow list for indexing post meta
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1636 Only load es wp query when needed
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1639 README updates: mention the way to run a specific test and pass extra args to PHPUnit.
  README.md
Labels: [Status] Ready to Deploy

#1637 Only send inconsistency alert in IRC in case it spans over two healthchecks.
  search/includes/classes/class-cache.php
  search/includes/classes/class-health-job.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#1640 Fixes filtering the photon domain with a scheme mismatch
  a8c-files.php
Labels: [Status] Needs Review

#1642 Prevent Woocommerce logs from being written to the Files Service
  plugin-fixes.php
Labels: [Status] Deployed

#1643 Return error codes for failed login attempts
  security.php
Labels: [Status] Ready to Deploy

#1641 Add vip_search_post_taxonomies_allow_list filter
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1626 Add opsgenie alerts for AllOptions
  alloptions-limit.php
Labels: [Status] Ready to Deploy

#1638 Add ending IRC notification for encloseme cleanup
  lib/class-vip-encloseme-cleanup.php
Labels: [Status] Ready to Deploy

#1644 Update es-wp-query subtree to latest
  package.json
  search/es-wp-query/adapters/vip-search.php
Labels: [Status] Ready to Deploy

#1648 Reduce _encloseme meta cleanup interval time
  lib/class-vip-encloseme-cleanup.php
Labels: [Status] Needs Review

#1649 Fix alloptions require
  alloptions-limit.php
Labels: [Status] Ready to Deploy
