Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-12, with the labels that each got.

#1894 Update jetpack-9.2 subtree to final 9.2 version
  jetpack-9.2/composer.json
  jetpack-9.2/jetpack.php
  jetpack-9.2/readme.txt
  jetpack-9.2/vendor/autoload.php
  jetpack-9.2/vendor/autoload_packages.php
  jetpack-9.2/vendor/composer/ClassLoader.php
  jetpack-9.2/vendor/composer/InstalledVersions.php
  jetpack-9.2/vendor/composer/LICENSE
  jetpack-9.2/vendor/composer/autoload_classmap.php
  jetpack-9.2/vendor/composer/autoload_real.php
  jetpack-9.2/vendor/composer/autoload_static.php
  jetpack-9.2/vendor/composer/installed.json
  jetpack-9.2/vendor/composer/installed.php
  jetpack-9.2/vendor/composer/jetpack_autoload_classmap.php
  jetpack-9.2/vendor/composer/platform_check.php
  jetpack-9.2/vendor/jetpack-autoloader/autoload_functions.php
  jetpack-9.2/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.2/vendor/jetpack-autoloader/class-manifest-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.2/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Needs Review

#1893 Fixes siteurl cache corruption with wp_insert_site
  wp-cli.php
Labels: [Status] Needs Review

#1896 Set Jetpack 9.2 as the default version
  jetpack.php
Labels: [Status] Do not deploy!

#1897 Ensure that a proper Jetpack version is loaded depending on WordPress version
  jetpack.php
Labels: [Status] Ready to Deploy

#1898 Fixes minor issues/warnings when using vip-search CLI
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Needs Review

#1899 Improve logging for failed HTTP requests to ElasticSearch
  search/includes/classes/class-search.php
Labels: [Status] Needs Review

#1905 Update/jetpack 9.2.1
  jetpack-9.2/_inc/build/instant-search/jp-search.bundle.asset.php
  jetpack-9.2/_inc/build/instant-search/jp-search.bundle.css
  jetpack-9.2/_inc/build/instant-search/jp-search.bundle.js
  jetpack-9.2/_inc/build/instant-search/jp-search.bundle.rtl.css
  jetpack-9.2/_inc/build/instant-search/jp-search.chunk-1-e052740f2f86553f7f9c.js
  jetpack-9.2/_inc/lib/debugger/class-jetpack-cxn-test-base.php
  jetpack-9.2/changelog.txt
  jetpack-9.2/jetpack.php
  jetpack-9.2/modules/calypsoify/class.jetpack-calypsoify.php
  jetpack-9.2/modules/masterbar/masterbar/class-masterbar.php
  jetpack-9.2/modules/theme-tools/compat/twentytwentyone.php
  jetpack-9.2/readme.txt
  jetpack-9.2/vendor/autoload.php
  jetpack-9.2/vendor/autoload_packages.php
  jetpack-9.2/vendor/composer/InstalledVersions.php
  jetpack-9.2/vendor/composer/autoload_real.php
  jetpack-9.2/vendor/composer/autoload_static.php
  jetpack-9.2/vendor/composer/installed.php
  jetpack-9.2/vendor/jetpack-autoloader/autoload_functions.php
  jetpack-9.2/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.2/vendor/jetpack-autoloader/class-manifest-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.2/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Ready to Deploy

#1904 Cleans up some phpcs issues
  package.json
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1907 Switched instructions to be in comments and added changelog tasks.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Ready to Deploy

#1909 Added additional failing tests from WP 5.6 to exclude list.
  bin/utils.sh
Labels: [Status] Deployed

#1906 phpunit-docker: Suffix db and network with unique names
  bin/download-wp-tests.sh
  bin/phpunit-docker.sh
Labels: [Status] Ready to Deploy

#1910 Remove exclusively core test jobs from CircleCi workflow.
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#1901 Update/wp jquery update test plugin
  debug.php
  debug/test-jquery-updates/5.6/assets/jquery-migrate-1.4.1.js
  debug/test-jquery-updates/5.6/class_wp_jquery_update_test.php
  debug/test-jquery-updates/5.6/readme.txt
  debug/test-jquery-updates/5.6/wp-jquery-update-test.php
Labels: [Status] Ready to Deploy

#1880 VIP Cache Manager: implement "Purge page and its assets" admin bar button
  package.json
  vip-cache-manager/js/admin-bar.js
  vip-cache-manager/vip-cache-manager.php
Labels: [Status] Ready to Deploy

#1911 Update old domains and WordPress.com references
  README-PUBLIC.md
  README.md
  cache/README.md
  gutenberg-ramp.php
  lib/proxy/ip-forward.php
  phpdoc.dist.xml
  rest-api/vip-endpoints.php
  shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php
  vip-cache-manager/ttl-manager.php
  vip-dashboard.php
  vip-helpers/vip-caching.php
  vip-helpers/vip-deprecated.php
  vip-helpers/vip-newrelic.php
  vip-helpers/vip-permastructs.php
  vip-helpers/vip-utils.php
  vip-jetpack/jetpack-mandatory.php
  vip-rest-api.php
  vip-support.php
Labels: [Status] Ready to Deploy

#1913 Support concatenation outside of VIP environments
  http-concat.php
Labels: [Status] Ready to Deploy

#1915 Fix syntax error
  vip-cache-manager/vip-cache-manager.php
Labels: [Status] Ready to Deploy

#1914 Added Changelog Description template to PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Ready to Deploy

#1881 Adds corrupted version detection
  search/includes/classes/class-search.php
  search/includes/classes/class-versioning.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Needs Review

#1916 Log to logstash when VIP Search ratelimiting starts.
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1919 Clears PHPCompatibility phpcs warnings
  000-debug/logger.php
Labels: [Status] Ready to Deploy

#1922 Cache Manager: update stats keys, track dashboard purge action
  vip-cache-manager/vip-cache-manager.php
Labels: [Status] Ready to Deploy

#1923 Add new fields to the site details data
  000-vip-init.php
  config/class-site-details-index.php
  tests/config/test-site-details-index.php
Labels: [Status] Ready to Deploy

#1924 Temporarily store site details data in logstash
  config/class-site-details-index.php
  config/class-sync.php
Labels: [Status] Ready to Deploy
