Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-05, with the labels that each got.

#1209 Adds command to output SQL for conversion.
  wp-cli/vip-go-convert-to-utf8mb4.php
Labels: [Status] Ready to Deploy

#1363 Debug bar panels: Fix Warning for Query Summary.
  vip-helpers/vip-debug-bar-panels.php
Labels: [Status] Ready to Deploy

#1580 Allow user indexing in Search
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1577 Added ratelimiting for indexing operations
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1579 Add support for query mirroring for offloaded queries
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1585 Enable query mirroring on category+archives for site 2160
  search/includes/classes/class-search.php
Labels: [Status] Needs Review

#1572 Akismet 4.1.5
  .deployignore
  akismet.php
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/changelog.txt
  akismet/class.akismet-admin.php
  akismet/readme.txt
  akismet/views/notice.php
Labels: [Status] Ready to Deploy

#1581 Hide the Instant Search toggle in Jetpack search settings
  vip-jetpack/css/admin-settings.css
  vip-jetpack/vip-jetpack.php
Labels: [Status] Ready to Deploy

#1586 Two Factor: re-enable FIDO UTF factor
  wpcom-vip-two-factor/set-providers.php
Labels: [Status] Ready to Deploy

#1588 Mirror the main taxonomy query on subset of sites
  search/includes/classes/class-search.php
Labels: [Status] Needs Review

#1590 Return true if subfolder path is missing trailing slash
  files/class-wp-filesystem-vip.php
Labels: [Status] Ready to Deploy

#1593 Add Search::query_es() helper
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1576 Filter `woocommerce_prevent_admin_access` to not block valid users from wp-admin
  two-factor.php
Labels: [Status] Ready to Deploy

#1591 Add caching layer to stats
  vip-helpers/vip-stats.php
Labels: [Status] Ready to Deploy

#1594 Add es-wp-query subtree for Search
  phpcs.xml.dist
  search/es-wp-query/.gitignore
  search/es-wp-query/.travis.yml
  search/es-wp-query/README.md
  search/es-wp-query/adapters/jetpack-search.php
  search/es-wp-query/adapters/searchpress.php
  search/es-wp-query/adapters/travis.php
  search/es-wp-query/adapters/vip-search.php
  search/es-wp-query/adapters/wpcom-vip.php
  search/es-wp-query/bin/install-es.sh
  search/es-wp-query/bin/install-wp-tests.sh
  search/es-wp-query/class-es-wp-date-query.php
  search/es-wp-query/class-es-wp-meta-query.php
  search/es-wp-query/class-es-wp-query-shoehorn.php
  search/es-wp-query/class-es-wp-query-wrapper.php
  search/es-wp-query/class-es-wp-tax-query.php
  search/es-wp-query/es-wp-query.php
  search/es-wp-query/functions.php
  search/es-wp-query/multisite.xml
  search/es-wp-query/phpcs.xml.dist
  search/es-wp-query/phpunit.xml.dist
  search/es-wp-query/tests/.DS_Store
  search/es-wp-query/tests/bootstrap.php
  search/es-wp-query/tests/query/author.php
  search/es-wp-query/tests/query/date.php
  search/es-wp-query/tests/query/dateQuery.php
  search/es-wp-query/tests/query/loggedIn.php
  search/es-wp-query/tests/query/metaQuery.php
  search/es-wp-query/tests/query/post.php
  search/es-wp-query/tests/query/query.php
  search/es-wp-query/tests/query/results.php
  search/es-wp-query/tests/query/shoehorn.php
  search/es-wp-query/tests/query/taxQuery.php
Labels: [Status] Ready to Deploy

#1595 Use es-wp-query for offloading
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1599 Add es-wp-query dev files to .deployignore
  .deployignore
Labels: [Status] Ready to Deploy

#1601 Debug Bar 1.0.1
  bin/upgrade-plugin.sh
  debug-bar.php
  debug-bar/css/debug-bar.css
  debug-bar/css/debug-bar.dev.css
  debug-bar/debug-bar.php
  debug-bar/panels/class-debug-bar-queries.php
  debug-bar/readme.txt
Labels: [Status] Ready to Deploy

#1602 Fix broken Jetpack connection during import cleanup
  000-vip-init.php
  vip-helpers/vip-utils.php
Labels: [Pri] High, [Status] Ready to Deploy

#1328 validate_attachments: Bugfix and feature update
  wp-cli/vip-migrations.php
Labels: [Status] Needs Review
