Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-11, with the labels that each got.

#1835 Bump phpcodesniffer-composer-installer to 0.7
  .circleci/config.yml
  composer.json
  composer.lock
Labels: [Status] Ready to Deploy

#1842 Adds gd installation to the build pipeline
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#1825 Unifies the es_failure flow
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1839 Adds admin notice plugin
  admin-notice.php
  admin-notice/admin-notice.php
  admin-notice/class-admin-notice-controller.php
  admin-notice/class-admin-notice.php
  admin-notice/conditions/class-date-condition.php
  admin-notice/conditions/interface-condition.php
  tests/admin-notice/conditions/test-class-admin-notice-time-condition.php
  tests/admin-notice/test-admin-notice-controller.php
  tests/admin-notice/test-class-admin-notice.php
Labels: [Status] Needs Review

#1834 Fix Failing core tests
  .circleci/config.yml
  README.md
  bin/utils.sh
Labels: [Status] Needs Review

#1845 Add/admin notice conditions
  admin-notice/admin-notice.php
  admin-notice/conditions/class-capability-condition.php
  admin-notice/conditions/class-wp-version-condition.php
  tests/admin-notice/conditions/test-class-capability-condition.php
  tests/admin-notice/conditions/test-class-date-condition.php
  tests/admin-notice/conditions/test-class-wp-version-condition.php
Labels: [Status] Ready to Deploy

#1846 Unignore some tests
  bin/utils.sh
Labels: [Status] Ready to Deploy

#1844 Set default Jetpack version to use the 9.1 subtree
  bin/utils.sh
  jetpack.php
Labels: [Status] Blocked

#1848 Cleans phppcs warnings
  tests/test-a8c-files-utils.php
  vip-plugins.php
Labels: [Status] Ready to Deploy

#1847 Add/admin notice dismiss
  admin-notice/admin-notice.php
  admin-notice/class-admin-notice-controller.php
  admin-notice/class-admin-notice.php
  admin-notice/js/script.js
  tests/admin-notice/test-class-admin-notice.php
Labels: [Status] Ready to Deploy

#1858 Update/linting debug logger
  000-debug/logger.php
Labels: [Status] Ready to Deploy

#1857 vip-plugins: link to post->permalink instead of post->meta->plugin_url
  vip-plugins/vip-plugins.php
Labels: [Status] Ready to Deploy

#1856 vip-plugins: "VIP Featured Plugins" -> "VIP Featured Partners"
  vip-plugins/vip-plugins.php
Labels: [Status] Ready to Deploy

#1861 Adjust health check cron interval to 1 hour
  search/includes/classes/class-health-job.php
Labels: [Status] Ready to Deploy

#1865 Unset skip-confirm before passing to EP for indexing
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy

#1827 Add wp vip cache purge-url subcommand
  wp-cli/vip-cache.php
Labels: [Status] Ready to Deploy

#1868 Add admin notice for WP 5.6 RC1
  admin-notice/admin-notice.php
  admin-notice/class-admin-notice.php
Labels: [Status] Ready to Deploy

#1869 Revert "Add admin notice for WP 5.6 RC1"
  admin-notice/admin-notice.php
  admin-notice/class-admin-notice.php
Labels: [Status] Ready to Deploy

#1873 Avoid a warning on Jetpack 9.1 when enabling instagram cache
  jetpack.php
  vip-helpers/vip-caching.php
Labels: [Status] Ready to Deploy

#1870 Dissmiss Notice Event by Onclick
  admin-notice/js/script.js
Labels: [Status] Ready to Deploy

#1864 Send prolonged rate limiting messages to logstash
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1863 Trigger a warning for prolonged rate limiting
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1876 Uprade query monitor 3.6.4->3.6.5.
  query-monitor.php
  query-monitor/assets/query-monitor.js
  query-monitor/classes/Activation.php
  query-monitor/classes/Backtrace.php
  query-monitor/classes/Hook.php
  query-monitor/classes/Util.php
  query-monitor/collectors/environment.php
  query-monitor/dispatchers/Html.php
  query-monitor/output/html/logger.php
  query-monitor/query-monitor.php
  query-monitor/readme.txt
Labels: [Status] Ready to Deploy

#1871 Update/vip utils phpcs issues
  tests/vip-helpers/vip-utils/include-vip-utils-include-plugin.php
  tests/vip-helpers/vip-utils/test-vip-utils-include-plugin.php
  tests/vip-helpers/vip-utils/test-vip-utils-remote-requests.php
  tests/vip-helpers/vip-utils/test-vip-utils-vip-is-jetpack-request.php
  tests/vip-helpers/vip-utils/test-vip-utils-vip-powered-wpcom-url.php
  tests/vip-helpers/vip-utils/test-vip-utils-wpcom-vip-file-get-contents.php
  tests/vip-helpers/vip-utils/test-vip-utils-wpcom-vip-is-feedservice-ua.php
  vip-helpers/vip-utils.php
Labels: [Status] Do not deploy!

#1878 Adds changes from 1.1.2 realease
  debug-bar.php
  debug-bar/css/debug-bar.css
  debug-bar/css/debug-bar.dev.css
  debug-bar/debug-bar.php
  debug-bar/panels/class-debug-bar-wp-http.php
  debug-bar/readme.txt
Labels: [Status] Ready to Deploy

#1884 Update Jetpack 9.2 subtree to 9.2-beta2
  jetpack-9.2/_inc/build/admin.asset.php
  jetpack-9.2/_inc/build/admin.css
  jetpack-9.2/_inc/build/admin.js
  jetpack-9.2/_inc/build/admin.rtl.css
  jetpack-9.2/_inc/build/images/green-star-b0ac6af62d4c43bd4d04ca6abb9c2e83.svg
  jetpack-9.2/_inc/build/style.min.css
  jetpack-9.2/_inc/build/style.min.rtl.css
  jetpack-9.2/changelog.txt
  jetpack-9.2/jetpack.php
  jetpack-9.2/modules/theme-tools.php
  jetpack-9.2/modules/theme-tools/compat/twentytwentyone-rtl.css
  jetpack-9.2/modules/theme-tools/compat/twentytwentyone.css
  jetpack-9.2/modules/theme-tools/compat/twentytwentyone.php
  jetpack-9.2/readme.txt
  jetpack-9.2/vendor/autoload.php
  jetpack-9.2/vendor/autoload_packages.php
  jetpack-9.2/vendor/composer/autoload_real.php
  jetpack-9.2/vendor/composer/autoload_static.php
  jetpack-9.2/vendor/jetpack-autoloader/autoload_functions.php
  jetpack-9.2/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.2/vendor/jetpack-autoloader/class-manifest-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.2/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.2/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Needs Review

#1877 Use sampling to reduce Search stat collection
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1888 Cleans_stale_notice
  admin-notice/admin-notice.php
  admin-notice/class-admin-notice-controller.php
  tests/admin-notice/test-admin-notice.php
  tests/admin-notice/test-class-admin-notice-controller.php
Labels: [Status] Ready to Deploy

#1879 Use filters for Search ratelimiting to allow per-site adjustments
  search/docs/ratelimiting.md
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1862 Update WordPress Importer to 0.7.0
  wordpress-importer/class-wp-import.php
  wordpress-importer/compat.php
  wordpress-importer/parsers.php
  wordpress-importer/parsers/class-wxr-parser-regex.php
  wordpress-importer/parsers/class-wxr-parser-simplexml.php
  wordpress-importer/parsers/class-wxr-parser-xml.php
  wordpress-importer/parsers/class-wxr-parser.php
  wordpress-importer/readme.txt
  wordpress-importer/wordpress-importer.php
Labels: [Status] Ready to Deploy

#1885 Add context to UA for Files API requests
  files/class-api-client.php
  tests/files/test-api-client.php
Labels: [Status] Needs Review

#1892 Changes the priority of QM shutdown to cover more operations
  query-monitor.php
Labels: [Status] Ready to Deploy

#1890 alloptions: Don't send alerts to nagios-vip
  alloptions-limit.php
Labels: [Status] Ready to Deploy

#1891 Adds defensive check when procesing ES response
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy
