Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-08, with the labels that each got.

#1696 Reduce add to queue stat usage
  search/includes/classes/class-queue.php
  search/includes/classes/class-versioning.php
  search/includes/classes/queue/class-cron.php
Labels: [Status] Ready to Deploy

#1697 Search: Add version support to document count validation job and command
  search/includes/classes/class-health-job.php
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#1701 Fix undeclared variable
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy

#1698 Search: Improve memory management for validate_contents
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  vip-helpers/vip-caching.php
  vip-helpers/vip-wp-cli.php
Labels: [Status] Needs Review

#1704 Disable core sitemap xml
  000-vip-init.php
Labels: [Status] Needs Review

#1708 Increase index ratelimiting threshold and decrease ratelimiting duration
  search/includes/classes/class-queue.php
Labels: [Status] Needs Review

#1710 Override ep prepare meta allowed protected keys
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1709 Fix parse_str() missing parameter deprecation
  tests/vip-helpers/test-wpcom-vip-set-image-quality-for-url.php
  vip-helpers/vip-media.php
Labels: [Pri] Low, [Status] Ready to Deploy, [Type] Maintenance

#1715 Skip currently broken tests
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1716 Reenable ep post meta filter override
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Blocked, [Status] Ready to Deploy

#1711 Add Feature flag lib
  000-vip-init.php
  lib/feature/class-feature.php
  tests/lib/feature/test-class-feature.php
Labels: [Status] Needs Review

#1718 Search: Support --network-wide in validate-counts commands
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy

#1703 Add support for WordPress 5.5 environment type
  000-vip-init.php
Labels: [Status] Ready to Deploy

#1712 Move `clearstatcache` call into the client class
  files/class-api-client.php
  files/class-vip-filesystem-stream-wrapper.php
Labels: [Status] Ready to Deploy

#1719 Enable comment type cron job for percentage
  000-vip-init.php
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#1722 Don't set sites as staging in Jetpack regardless of env type
  000-vip-init.php
Labels: [Status] Needs Review

#1724 npm audit fix
  package-lock.json
Labels: [Status] Needs Review

#1725 Bump comment type update job to running on 50% of sites
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#1726 Bump comment type job percentage to 75%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#1727 Disable above compat admin notice for EP
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1706 Block new `_encloseme` post metadata from being added
  performance/do-pings.php
  tests/performance/test-do-pings.php
Labels: [Status] Ready to Deploy

#1729 Enable comment type update cron job for all sites
  000-vip-init.php
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#1736 Features: Use a site_id() function instead of defaulting to FILES_CLIENT_SITE_ID
  lib/feature/class-feature.php
  tests/lib/feature/test-class-feature.php
Labels: [Status] Needs Review

#1739 Test nightly WP against PHP 7.4
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#1741 Fix file stats cache reset on upload
  files/class-api-client.php
  tests/files/test-api-client.php
Labels: [Status] Ready to Deploy

#1733 Search: implement a confirmation prompt before executing destructive CLI commands
  search/includes/classes/class-search.php
  search/includes/classes/commands/class-corecommand.php
  search/includes/classes/commands/class-versioncommand.php
Labels: [Status] Ready to Deploy

#1735 Search: Add Health::reconcile_diff method to allow for the correction of index inconsistencies.
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy
