Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-02, with the labels that each got.

#1432 Log a warning with more details about api blocks
  two-factor.php
Labels: [Status] Needs Review

#1411 Improvements on ElasticSearch validation command
  000-vip-init.php
  elasticsearch/commands/class-health-command.php
  elasticsearch/elasticsearch.php
  elasticsearch/includes/classes/class-elasticsearch.php
  elasticsearch/includes/classes/class-health.php
  elasticsearch/includes/classes/commands/class-healthcommand.php
  tests/elasticsearch/test-class-elasticsearch.php
Labels: [Status] Needs Review

#1435 Add missing 'use' statement for WP_Error class namespace
  elasticsearch/includes/classes/class-health.php
Labels: [Status] Ready to Deploy

#1437 Get accurate total count from Elasticsearch
  elasticsearch/includes/classes/class-health.php
Labels: [Status] Ready to Deploy

#1438 ES Health: Cleanup diff output
  elasticsearch/includes/classes/class-health.php
Labels: [Status] Ready to Deploy

#1436 Add Elasticsearch health check cronjob
  elasticsearch/includes/classes/class-elasticsearch.php
  elasticsearch/includes/classes/class-health-job.php
Labels: [Status] Needs Review

#1440 Add PHPCS Diffing
  .circleci/config.yml
  .deployignore
  bin/phpcs-diff.sh
  composer.json
  composer.lock
  phpcs.xml.dist
Labels: [Status] Needs Review

#1441 Start health check only on production env
  elasticsearch/includes/classes/class-elasticsearch.php
Labels: [Status] Needs Review

#1451 Fix typo in variable name
  elasticsearch/includes/classes/class-health-job.php
Labels: [Status] Ready to Deploy

#1447 Deactivate jetpack widgets when VIP search is enabled
  elasticsearch/includes/classes/class-elasticsearch.php
  tests/elasticsearch/test-class-elasticsearch.php
Labels: [Status] Ready to Deploy

#1449 Fix fatal error in validate-health command
  elasticsearch/includes/classes/class-health.php
  elasticsearch/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy

#1456 Switch Elasticsearch auto-loader to require_once
  elasticsearch/elasticsearch.php
Labels: [Status] Ready to Deploy

#1455 Fix Search health check cron
  elasticsearch/includes/classes/class-health-job.php
Labels: [Status] Ready to Deploy

#1442 Shared plugins: Add defensive code to fix Warning
  vip-plugins/vip-plugins.php
Labels: [Status] Ready to Deploy

#1458 Block all API requests for all 2fa users
  two-factor.php
Labels: [Status] Ready to Deploy

#1439 IRC/Slack alert when cron control cron option is uncacheable
  001-cron.php
Labels: [Status] Ready to Deploy

#1459 Add EP_DASHBOARD_SYNC constant
  elasticsearch/includes/classes/class-elasticsearch.php
Labels: [Status] Ready to Deploy

#1452 Separate ElasticPress indexing from using the index
  elasticsearch/includes/classes/class-elasticsearch.php
Labels: [Status] Needs Review

#1457 Remove Vary: Origin override
  security.php
Labels: [Status] Ready to Deploy

#1465 Fix missing require for es health class and typo
  elasticsearch/includes/classes/class-elasticsearch.php
  elasticsearch/includes/classes/class-health-job.php
  elasticsearch/includes/classes/commands/class-healthcommand.php
  tests/elasticsearch/includes/classes/commands/test-class-healthcommand.php
  tests/elasticsearch/includes/classes/test-class-healthjob.php
  tests/elasticsearch/test-class-elasticsearch.php
Labels: [Status] Ready to Deploy

#1467 Only alert when diff is not 0
  elasticsearch/includes/classes/class-health-job.php
  tests/elasticsearch/includes/classes/test-class-healthjob.php
Labels: [Status] Needs Review

#1468 Revert "Only alert when diff is not 0"
  elasticsearch/includes/classes/class-health-job.php
  tests/elasticsearch/includes/classes/test-class-healthjob.php
Labels: [Status] Needs Review

#1469 Revert "Revert "Only alert when diff is not 0""
  elasticsearch/includes/classes/class-health-job.php
  tests/elasticsearch/includes/classes/test-class-healthjob.php
Labels: [Status] Needs Review

#1448 VIP Search: Increase timeouts for bulk indexing requests
  elasticsearch/includes/classes/class-elasticsearch.php
  tests/elasticsearch/test-class-elasticsearch.php
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1470 Manually setup EP Debug Bar logging due to plugins_loaded already firing
  elasticsearch/includes/classes/class-elasticsearch.php
Labels: [Status] Ready to Deploy

#1475 Add custom headers to all ElasticSearch requests
  elasticsearch/includes/classes/class-elasticsearch.php
Labels: [Status] Ready to Deploy

#1454 Add option to disable Elasticsearch healthcheck job
  elasticsearch/includes/classes/class-elasticsearch.php
  elasticsearch/includes/classes/class-health-job.php
  tests/elasticsearch/test-class-elasticsearch.php
Labels: [Status] Ready to Deploy

#1466 Add Opsgenie alert helpers
  lib/utils/class-alerts.php
  tests/lib/utils/test-alerts.php
Labels: [Status] Has Feedback
