Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-03, with the labels that each got.

#1477 Run phpcs through eslines
  .circleci/config.yml
  .eslines.json
  .gitignore
  bin/phpcs-diff.sh
  bin/phpcs-eslint-report.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  phpcs.xml.dist
Labels: [Status] Needs Review

#1478 Include new Alerts class file
  000-vip-init.php
Labels: [Status] Ready to Deploy

#1480 Replace Elasticsearch references with VIP Search
  000-vip-init.php
  elasticsearch/elasticsearch.php
  elasticsearch/includes/classes/class-dashboard.php
  elasticsearch/includes/classes/class-elasticsearch.php
  elasticsearch/includes/classes/class-health-job.php
  elasticsearch/includes/classes/class-health.php
  elasticsearch/includes/classes/commands/class-healthcommand.php
  tests/elasticsearch/includes/classes/commands/test-class-healthcommand.php
  tests/elasticsearch/includes/classes/test-class-healthjob.php
  tests/elasticsearch/test-class-elasticsearch.php
Labels: [Status] Needs Review

#1482 Disable document indexing feature
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1476 Standardize two factor authentication SMS messages
  tests/wpcom-vip-two-factor/sms-provider.php
  wpcom-vip-two-factor/sms-provider.php
Labels: [Status] In Progress

#1484 Add retries and random load balancing for EP_HOST
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1486 Add husky to enforce phpcs on pre-commit
  .huskyrc.json
  README.md
  package-lock.json
  package.json
Labels: [Status] Has Feedback, [Status] Needs Review

#1491 Search: Hide Authorization header in EP Debug Bar request log
  search/includes/classes/class-search.php
  search/includes/functions/ep-get-query-log.php
Labels: [Status] Ready to Deploy

#1492 Fix health check failure notifications related to index counts
  search/includes/classes/class-health.php
Labels: [Status] Ready to Deploy

#1494 Fix 2fa SMS messages to include path for multisite subsites
  wpcom-vip-two-factor/sms-provider.php
Labels: [Status] Needs Review

#1497 phpcs: Ignore wpcom_vip_irc function rule
  phpcs.xml.dist
Labels: [Status] Needs Review

#1495 Alerts: Send option uncacheable alerts to the critical channel
  001-cron.php
Labels: [Status] Ready to Deploy

#1501 Temporarily force disable user indexing
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1500 Removed gutenburg alert
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1493 Add index content validation
  phpcs.xml.dist
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-health.php
Labels: [Status] Has Feedback

#1502 More validation checks for ep_pre_request_host
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1445 Limit calls to `Two_Factor_Core::is_user_using_two_factor()`
  two-factor.php
Labels: [Status] Ready to Deploy

#1504 Allow queries during indexing
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1503 Add the missing WP_EP_DEBUG constant
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1499 Add logstash support
  000-vip-init.php
  logstash/class-logger.php
  logstash/logstash.php
  tests/logstash/test-logger.php
Labels: [Status] Needs Review

#1511 PHPCS: Add minimum_supported_wp_version of 5.3
  phpcs.xml.dist
Labels: [Status] Needs Review, [Type] Maintenance

#1512 Don't nerf $wp_object_cache->stats in stop_the_insanity()
  vip-helpers/vip-wp-cli.php
Labels: [Status] Ready to Deploy

#1514 Fix SMS codes with leading zeros
  tests/wpcom-vip-two-factor/sms-provider.php
  wpcom-vip-two-factor/sms-provider.php
Labels: [Status] Ready to Deploy

#1515 Update two-factor to calculate `is_using_two_factor` outside of map_m…
  two-factor.php
Labels: [Status] Needs Review

#1516 Add facet query filters to search
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1508 Added yaml config for search testing
  tests/search/data/test_fixtures.yml
Labels: [Status] Needs Review

#1517 Remove test from the Site Health tool page
  001-core.php
Labels: [Status] Ready to Deploy

#1519 Disable Jetpack Search offload when ElasticPress is being used
  000-vip-init.php
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1513 Check type is numeric first
  lib/wpcom-error-handler/wpcom-error-handler.php
Labels: [Status] Ready to Deploy

#1518 Remove/php modules site health
  001-core.php
Labels: [Status] Ready to Deploy

#1520 Allow enabling search query integration via an option
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1521 Add StatsD library
  000-vip-init.php
  lib/statsd/class-statsd.php
Labels: [Status] Ready to Deploy

#1524 Add Host-Header header
  000-vip-init.php
Labels: [Status] Ready to Deploy

#1530 Update logstash lib to write to a logfile
  logstash/class-logger.php
  tests/logstash/test-logger.php
Labels: [Status] Ready to Deploy
