Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-07, with the labels that each got.

#1653 Add random stagger to _encloseme meta cleanup start time
  lib/class-vip-encloseme-cleanup.php
Labels: [Status] Needs Review

#1650 Record added_to_queue stat
  search/includes/classes/class-queue.php
Labels: [Status] Ready to Deploy

#1652 Add stat tracking for queue wait times
  search/includes/classes/class-queue.php
  search/includes/classes/class-queuewaittimejob.php
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1655 Fix alert service endpoint
  lib/utils/class-alerts.php
  tests/lib/utils/test-alerts.php
Labels: [Status] Ready to Deploy

#1647 Added statsd gauge for post index current field count
  search/includes/classes/class-fieldcountgaugejob.php
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#1651 Record processed_from_queue stat
  search/includes/classes/class-queue.php
Labels: [Status] Ready to Deploy

#1654 Fix index healthchecks during indexing
  search/includes/classes/class-health-job.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Needs Review

#1657 Fix/alerts endpoint
  alloptions-limit.php
Labels: [Status] Ready to Deploy

#1646 Search: Add base index versioning support
  search/includes/classes/class-search.php
  search/includes/classes/class-versioning.php
  tests/search/includes/classes/test-class-versioning.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1656 Add Search versioning CLI commands
  search/includes/classes/class-search.php
  search/includes/classes/class-versioning.php
  search/includes/classes/commands/class-versioncommand.php
  tests/search/includes/classes/test-class-versioning.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1659 Search: Add version support to index CLI command
  search/includes/classes/class-search.php
  search/includes/classes/class-versioning.php
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy

#1661 Async indexing now enabled by default
  search/includes/classes/class-queue.php
Labels: [Status] Ready to Deploy

#1663 Fix queue sweeper cron and stats
  search/includes/classes/class-queue.php
  search/includes/classes/queue/class-cron.php
Labels: [Status] Needs Review

#1664 Use update_stats directly
  search/includes/classes/class-queue.php
Labels: [Status] Ready to Deploy

#1658 Reindex post if post meta is in allow list
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1667 Remove wp-cli-to-cron
  vip-wp-cli-to-cron.php
Labels: [Status] Ready to Deploy

#1662 Search: Add index_version column to queue table
  search/includes/classes/queue/class-schema.php
Labels: [Status] Ready to Deploy

#1666 Schedule multiple processor jobs on shorter interval
  search/includes/classes/queue/class-cron.php
Labels: [Status] Ready to Deploy

#1669 README: Add note about lando test
  README.md
Labels: [Status] Ready to Deploy

#1670 Search: Switch to admin_menu hook for altering menu
  search/includes/classes/class-dashboard.php
Labels: [Status] Ready to Deploy

#1668 Search: update query integration argument from 'es' to 'vip_search_enabled' to eliminate the chances of conflicts with client code
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1672 Search: Support new HA endpoint structure in stat names
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1671 Search: Add version support to queue (continued)
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1677 Disable health checks for more IDs
  search/includes/classes/class-health-job.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Needs Review

#1681 Fix broken CircleCI tests
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#1686 Add permission_callback to test-cache-ttl-manager-rest.php
  tests/test-cache-ttl-manager-rest.php
Labels: [Status] Needs Review

#1687 Look for all line ending types in mail test for checking tracking
  tests/test-vip-mail.php
Labels: [Status] Needs Review

#1685 QM: Re-add previously ignored output directory
  .gitignore
  query-monitor/output/Headers.php
  query-monitor/output/Html.php
  query-monitor/output/headers/overview.php
  query-monitor/output/headers/php_errors.php
  query-monitor/output/headers/redirects.php
  query-monitor/output/html/admin.php
  query-monitor/output/html/assets.php
  query-monitor/output/html/caps.php
  query-monitor/output/html/conditionals.php
  query-monitor/output/html/db_callers.php
  query-monitor/output/html/db_components.php
  query-monitor/output/html/db_dupes.php
  query-monitor/output/html/db_queries.php
  query-monitor/output/html/debug_bar.php
  query-monitor/output/html/environment.php
  query-monitor/output/html/hooks.php
  query-monitor/output/html/http.php
  query-monitor/output/html/languages.php
  query-monitor/output/html/logger.php
  query-monitor/output/html/overview.php
  query-monitor/output/html/php_errors.php
  query-monitor/output/html/request.php
  query-monitor/output/html/theme.php
  query-monitor/output/html/timing.php
  query-monitor/output/html/transients.php
Labels: [Impact] High, [Pri] Blocker, [Type] Bug

#1689 Use full file path for file service caching
  files/class-api-cache.php
  tests/files/test-vip-filesystem-api-cache.php
Labels: [Status] Ready to Deploy

#1692 Search: Create the new index in ES when a version is registered
  search/includes/classes/class-versioning.php
  search/includes/classes/commands/class-versioncommand.php
Labels: [Pri] Blocker, [Status] Ready to Deploy

#1693 Add unified lint command
  .circleci/config.yml
  package.json
Labels: [Status] Needs Review

#1676 Search: Keep all index versions in sync
  search/includes/classes/class-queue.php
  search/includes/classes/class-versioning.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Ready to Deploy

#1694 Remove health check exclusions
  search/includes/classes/class-health-job.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#1695 Search: Add/ delete index version command
  search/includes/classes/class-versioning.php
  search/includes/classes/commands/class-versioncommand.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Ready to Deploy
