Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-01, with the labels that each got.

#1395 Add vip_safe_wp_remote_request()
  tests/vip-helpers/vip-utils/test-vip-utils-remote-requests.php
  tests/vip-helpers/vip-utils/test-vip-utils-resized-attachments.php
  vip-helpers/vip-utils.php
Labels: [Status] Needs Review

#1390 Streamwrapper: Cache file_exists requests
  files/class-api-cache.php
  files/class-api-client.php
  tests/files/test-vip-filesystem-api-cache.php
Labels: [Status] Ready to Deploy

#1405 Use forked version of ElasticPress
  .gitmodules
Labels: [Status] Needs Review

#1397 Fix OOM errors on large video uploads
  files/class-api-cache.php
  files/class-api-client.php
  files/class-vip-filesystem-stream-wrapper.php
  files/class-wp-filesystem-vip-uploads.php
  tests/files/test-api-client.php
  tests/files/test-vip-filesystem-api-cache.php
  tests/files/test-wp-filesystem-vip-uploads.php
Labels: [Status] Ready to Deploy

#1359 Akismet 4.1.3
  akismet.php
  akismet/_inc/akismet.css
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet-admin.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/activate.php
  akismet/views/connect-jp.php
  akismet/views/enter.php
  akismet/views/notice.php
  akismet/views/predefined.php
  akismet/views/setup.php
  akismet/views/start.php
  akismet/views/title.php
Labels: [Status] Needs Review

#1414 Add some ElasticPress-related files to ignore
  .deployignore
Labels: [Status] Ready to Deploy

#1419 Add stats to track blocking of 2fa API users
  two-factor.php
  wpcom-vip-two-factor/set-providers.php
Labels: [Status] Needs Review

#1416 IP Forward: Remove mentions of preferred methods from inline docs
  lib/proxy/ip-forward.php
Labels: [Status] Needs Review

#1421 VaultPress: skip some files
  vaultpress.php
Labels: [Status] Retro Review

#1424 Block API requests for users with 2fa enabled
  two-factor.php
Labels: [Status] Needs Review

#1429 Make Jetpack_Start_CLI_Command::maybe_create_user not die silently on error
  jetpack-start/wp-cli-api.php
Labels: [Pri] High, [Status] Needs Review

#1431 Enforce the jetpack_active_plan option
  vip-jetpack/vip-jetpack.php
Labels: [Status] Needs Review
