Repository Automattic/vip-go-mu-plugins, pull requests merged in 2020-10, with the labels that each got.

#1791 Update/core tests with mu plugins
  .circleci/config.yml
  bin/utils.sh
Labels: [Status] Needs Review

#1792 Speeding up git checkout for circleCI jobs
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#1787 Support multiple Jetpack versions
  bin/add-jetpack-subtree.sh
  bin/update-jetpack-subtree.sh
  jetpack.php
Labels: [Status] Ready to Deploy

#1793 Removes elasticpress menu links
  search/includes/classes/class-dashboard.php
Labels: [Status] Ready to Deploy

#1780 Search: switch vip-search index --network-wide to spawn child processes instead of using switch_to_blog
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy

#1786 Async Cmd Scheduler: trim whitespaces from Slack audit messages, adjust message format to ensure there's no misrendered markdown
  wp-cli/class-async-scheduler-command.php
Labels: [Status] Ready to Deploy

#1797 Fix arguments for WP_Error invalid-indexable for queue
  search/includes/classes/class-queue.php
Labels: [Status] Ready to Deploy

#1796 Clear queue of related jobs on index version delete
  search/includes/classes/class-queue.php
  search/includes/classes/class-versioning.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1799 Skip indexing job from queue if index version not found
  search/includes/classes/class-queue.php
Labels: [Status] Ready to Deploy

#1803 Added limit to index version count
  search/includes/classes/class-versioning.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Ready to Deploy

#1805 Update jetpack-9.0 subtree to version 9.0.1
  jetpack-9.0/changelog.txt
  jetpack-9.0/class.jetpack.php
  jetpack-9.0/jetpack.php
  jetpack-9.0/readme.txt
  jetpack-9.0/vendor/autoload.php
  jetpack-9.0/vendor/autoload_packages.php
  jetpack-9.0/vendor/automattic/jetpack-connection/src/class-manager.php
  jetpack-9.0/vendor/automattic/jetpack-connection/src/class-nonce-handler.php
  jetpack-9.0/vendor/composer/autoload_classmap.php
  jetpack-9.0/vendor/composer/autoload_real.php
  jetpack-9.0/vendor/composer/autoload_static.php
  jetpack-9.0/vendor/composer/installed.json
  jetpack-9.0/vendor/composer/jetpack_autoload_classmap.php
  jetpack-9.0/vendor/composer/jetpack_autoload_filemap.php
  jetpack-9.0/vendor/jetpack-autoloader/autoload_functions.php
  jetpack-9.0/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.0/vendor/jetpack-autoloader/class-manifest-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.0/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Ready to Deploy

#1806 Jetpack 9.0 as new default
  jetpack.php
Labels: [Status] Ready to Deploy

#1795 Tracks indexing job lenght
  composer.json
  composer.lock
  lib/statsd/class-statsd.php
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1808 Update/jetpack9.0.2
  jetpack-9.0/_inc/blocks/editor-beta.asset.php
  jetpack-9.0/_inc/blocks/editor-beta.js
  jetpack-9.0/_inc/blocks/editor-experimental.asset.php
  jetpack-9.0/_inc/blocks/editor-experimental.js
  jetpack-9.0/_inc/blocks/editor.asset.php
  jetpack-9.0/_inc/blocks/editor.js
  jetpack-9.0/_inc/build/admin.asset.php
  jetpack-9.0/_inc/build/admin.js
  jetpack-9.0/_inc/lib/class-jetpack-tweetstorm-helper.php
  jetpack-9.0/_inc/lib/class.media-extractor.php
  jetpack-9.0/extensions/blocks/publicize/twitter/options.js
  jetpack-9.0/functions.opengraph.php
  jetpack-9.0/jetpack.php
  jetpack-9.0/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
  jetpack-9.0/modules/shortcodes/instagram.php
  jetpack-9.0/readme.txt
  jetpack-9.0/vendor/autoload.php
  jetpack-9.0/vendor/autoload_packages.php
  jetpack-9.0/vendor/automattic/jetpack-connection/src/class-client.php
  jetpack-9.0/vendor/automattic/jetpack-connection/src/class-manager.php
  jetpack-9.0/vendor/automattic/jetpack-connection/src/class-rest-authentication.php
  jetpack-9.0/vendor/composer/autoload_real.php
  jetpack-9.0/vendor/composer/autoload_static.php
  jetpack-9.0/vendor/composer/installed.json
  jetpack-9.0/vendor/composer/jetpack_autoload_classmap.php
  jetpack-9.0/vendor/composer/jetpack_autoload_filemap.php
  jetpack-9.0/vendor/jetpack-autoloader/autoload_functions.php
  jetpack-9.0/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.0/vendor/jetpack-autoloader/class-manifest-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.0/vendor/jetpack-autoloader/class-version-selector.php
  jetpack.php
Labels: [Status] Needs Review

#1809 Update/request counters
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1810 FORNO-283: Increase timeout for file deletion
  files/class-api-client.php
Labels: [Status] Ready to Deploy

#1812 Search: implement stale queue alerts
  search/includes/classes/class-queuewaittimejob.php
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1811 Update/rate limiting stats
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1813 search-statsd: cleanup per site metrics
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  search/includes/classes/class-versioning.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1816 Search: Consider stuck `running` jobs as deadlocked too
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1822 Update/jetpack9.0.2.1
  jetpack-9.0/jetpack.php
  jetpack-9.0/modules/shortcodes/facebook.php
  jetpack-9.0/vendor/autoload.php
  jetpack-9.0/vendor/autoload_packages.php
  jetpack-9.0/vendor/composer/autoload_real.php
  jetpack-9.0/vendor/composer/autoload_static.php
  jetpack-9.0/vendor/jetpack-autoloader/autoload_functions.php
  jetpack-9.0/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.0/vendor/jetpack-autoloader/class-manifest-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.0/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.0/vendor/jetpack-autoloader/class-version-selector.php
  jetpack.php
Labels: [Status] Ready to Deploy

#1823 Search: Update es-wp-query subtree with fix for user_nicename field
  search/es-wp-query/adapters/vip-search.php
Labels: [Status] Ready to Deploy

#1818 Adds IRC/slack alert for long query limiting
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1820 Update/alert on prolonged index limiting
  search/includes/classes/class-queue.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Ready to Deploy

#1819 Add VIP Request Block utility library
  lib/class-vip-request-block.php
Labels: [Status] Ready to Deploy

#1821 Adds IRC/slack alert for too many fields
  search/includes/classes/class-fieldcountgaugejob.php
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1824 Solve a memory leak in ElasticPress when WP_DEBUG is enabled
  search/includes/classes/class-search.php
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy

#1817 Added test for process_jobs
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Has Feedback

#1828 Remove curly braces syntax for array access
  lib/class-apc-cache-interceptor.php
Labels: [Status] Ready to Deploy

#1826 Akismet 4.1.7
  akismet.php
  akismet/akismet.php
  akismet/changelog.txt
  akismet/class.akismet-admin.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/stats.php
Labels: [Status] Needs Review
