Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-09, with the labels that each got.

#2393 Use __return_zero filter for files filter
  files/class-vip-filesystem.php
Labels: [Status] Ready to Deploy

#2402 Removing Jetpack check for old WP versions
  .circleci/config.yml
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#2403 Adding release script
  README.md
  bin/create-release.sh
Labels: [Status] Ready to Deploy

#2401 Updating Akismet to 4.1.12
  akismet.php
  akismet/_inc/akismet.css
  akismet/akismet.php
  akismet/class.akismet.php
  akismet/readme.txt
Labels: [Status] Ready to Deploy

#2384 Validate only the active indexables instead of trying post and user no matter what (and failing to validate term and comment)
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#2406 Removing legacy Elasticsearch code
  shared-plugins/vip-go-elasticsearch/class.es-wpcom-searchresult-posts-iterator.php
  shared-plugins/vip-go-elasticsearch/vip-go-elasticsearch.php
  tests/test-vip-plugins.php
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#2411 Adding additional checks on correct Jetpack Connection
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#2410 Making Jetpack 10.1 default version
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#2414 Fix phpcs issues for admin-notice plugin
  admin-notice.php
  admin-notice/class-admin-notice-controller.php
  admin-notice/class-admin-notice.php
  admin-notice/conditions/class-date-condition.php
Labels: [Status] Ready to Deploy, [Component] Code Standards

#2416 Fix "Class 'Automattic\VIP\Helpers\WP_Error' not found" in `User_Cleanup::revoke_roles_for_users()`
  tests/vip-helpers/test-class-user-cleanup.php
  vip-helpers/class-user-cleanup.php
Labels: [Status] Ready to Deploy

#2420 Ignoring dev-env related file
  .gitignore
Labels: [Status] Ready to Deploy

#2417 Don't log the false returned from Queue Sweeper's schedule_batch_job
  search/includes/classes/queue/class-cron.php
Labels: [Status] Ready to Deploy, [Component] Search

#2418 Remove Jetpack Search Menu if Enterprise Search is enabled
  search/includes/classes/class-search.php
  search/search.php
Labels: [Status] Ready to Deploy, [Component] Search, [Component] Jetpack

#2419 Prevent newrelic transaction name overrides during cron
  vip-helpers/vip-newrelic.php
Labels: [Status] Ready to Deploy

#2425 Update wp-parsely to 2.5.1
  wp-parsely-2.5/CHANGELOG.md
  wp-parsely-2.5/README.md
  wp-parsely-2.5/build/init-api.asset.php
  wp-parsely-2.5/build/init-api.js
  wp-parsely-2.5/composer.json
  wp-parsely-2.5/src/class-parsely.php
  wp-parsely-2.5/src/js/lib/init-api/index.js
  wp-parsely-2.5/wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#2049 Introduce vip-woocommerce module
  plugin-fixes.php
  vip-woocommerce.php
  vip-woocommerce/logging.php
  vip-woocommerce/vip-woocommerce.php
Labels: [Status] Ready to Deploy

#2424 Search: Health - validate counts: prevent potential fatal for term and comment indexables.
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#2429 Cache Manager: Fix code style issues (2/2)
  phpcs.xml.dist
  vip-cache-manager/vip-cache-manager.php
Labels: [Component] Code Standards

#2426 Removed legacy code which broke comment counts.
  performance/vip-tweaks.php
  vip-helpers/vip-caching.php
Labels: [Status] Ready to Deploy

#2432 Update wp-parsely to 2.5.2
  phpcs.xml.dist
  wp-parsely-2.5/.github/workflows/cs-lint.yml
  wp-parsely-2.5/.phpcs.xml.dist
  wp-parsely-2.5/CHANGELOG.md
  wp-parsely-2.5/README.md
  wp-parsely-2.5/build/admin-page.asset.php
  wp-parsely-2.5/build/admin-page.js
  wp-parsely-2.5/build/init-api.asset.php
  wp-parsely-2.5/build/init-api.js
  wp-parsely-2.5/build/recommended-widget.asset.php
  wp-parsely-2.5/build/recommended-widget.js
  wp-parsely-2.5/composer.json
  wp-parsely-2.5/package-lock.json
  wp-parsely-2.5/package.json
  wp-parsely-2.5/phpunit.xml.dist
  wp-parsely-2.5/src/class-parsely-recommended-widget.php
  wp-parsely-2.5/src/class-parsely.php
  wp-parsely-2.5/src/js/lib/cookies/index.js
  wp-parsely-2.5/src/js/lib/cookies/utils.js
  wp-parsely-2.5/src/js/lib/personalization.js
  wp-parsely-2.5/src/js/widgets/recommended/index.js
  wp-parsely-2.5/src/parsely-settings.php
  wp-parsely-2.5/tests/GetCurrentUrlTest.php
  wp-parsely-2.5/tests/Integrations/AmpTest.php
  wp-parsely-2.5/tests/Integrations/FbiaTest.php
  wp-parsely-2.5/tests/OtherTest.php
  wp-parsely-2.5/tests/StructuredData/AuthorArchiveTest.php
  wp-parsely-2.5/tests/StructuredData/BlogArchiveTest.php
  wp-parsely-2.5/tests/StructuredData/HomePageTest.php
  wp-parsely-2.5/tests/StructuredData/NonPostTestCase.php
  wp-parsely-2.5/tests/StructuredData/SinglePageTest.php
  wp-parsely-2.5/tests/StructuredData/SinglePostTest.php
  wp-parsely-2.5/tests/StructuredData/TermArchiveTest.php
  wp-parsely-2.5/tests/TestCase.php
  wp-parsely-2.5/tests/bootstrap.php
  wp-parsely-2.5/tests/class-all-test.php
  wp-parsely-2.5/tests/js/lib/personalization.test.js
  wp-parsely-2.5/tests/js/unit/lib/cookies.test.js
  wp-parsely-2.5/tests/recommended-api-test.php
  wp-parsely-2.5/tests/structured-data/class-archive-post-test.php
  wp-parsely-2.5/tests/structured-data/class-single-post-test.php
  wp-parsely-2.5/views/repeated-metas.php
  wp-parsely-2.5/wp-parsely.php
Labels: [Status] Has Feedback, [Status] Ready to Deploy, [Component] Parse.ly

#2423 Using next-gen CircleCI images
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#2427 Add a filter to check if the current user can purge the cache
  vip-cache-manager/vip-cache-manager.php
Labels: [Type] Enhancement, [Status] Ready to Deploy

#2405 Annotate the parsely option with meta_type => repeated_metas
  tests/parsely/test-mu-parsely-integration.php
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#2434 Revert "Disabling WebP images upload temporarily"
  misc.php
Labels: [Status] Ready to Deploy

#2444 Search Dev Tools: bump Prism.js version bump to 1.25.0
  search/search-dev-tools/build/bundle.a0db3.esm.js
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
Labels: [Status] Ready to Deploy, [Component] Search

#2445 Re-work streamWrapper debug using log2logstash and more detailed debug backtrace
  files/class-vip-filesystem-stream-wrapper.php
Labels: [Status] Ready to Deploy

#2449 Report correct name during settings check
  search/includes/classes/class-health.php
  tests/search/includes/classes/test-class-health.php
Labels: [Status] Ready to Deploy

#2450 Updating Parsely plugin loading hook
  tests/parsely/test-mu-parsely-integration.php
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#2454 Change default Parse.ly to 2.6
  wp-parsely.php
Labels: [Status] Needs Review, [Component] Parse.ly
