Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-01, with the labels that each got.

#1908 Added proposal requirements to PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Do not deploy!, [Status] Needs Review

#1920 Clears PHPCompatibility phpcs warnings wpcom-error-handler
  lib/wpcom-error-handler/wpcom-error-handler.php
Labels: [Status] Ready to Deploy

#1921 Updates the way vip-search versioning information is stored
  search/includes/classes/class-versioning.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Ready to Deploy

#1929 IpUtils - clearing up phpcs errors
  lib/proxy/ip-forward.php
  lib/proxy/ip-utils.php
  tests/test-lib-proxy-ip-utils.php
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1927 Adjusted shutdown priorities for query monitor dispatch and log2logstash
  logstash/class-logger.php
  query-monitor.php
Labels: [Status] Ready to Deploy

#1933 Do not validate counts if Search index doesn't exist
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy

#1935 Added ability to set fixed timestamps in Search for testing
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1928 Akismet 4.1.8
  akismet.php
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet.php
  akismet/readme.txt
Labels: [Status] Ready to Deploy

#1936 Update Jetpack-9.3 subtree to the final 9.3 release
  bin/add-jetpack-subtree.sh
  jetpack-9.3/_inc/blocks/editor-beta.asset.php
  jetpack-9.3/_inc/blocks/editor-beta.css
  jetpack-9.3/_inc/blocks/editor-beta.rtl.css
  jetpack-9.3/_inc/blocks/editor-experimental.asset.php
  jetpack-9.3/_inc/blocks/editor-experimental.css
  jetpack-9.3/_inc/blocks/editor-experimental.rtl.css
  jetpack-9.3/_inc/blocks/editor.asset.php
  jetpack-9.3/_inc/blocks/editor.css
  jetpack-9.3/_inc/blocks/editor.rtl.css
  jetpack-9.3/_inc/blocks/story/view.asset.php
  jetpack-9.3/_inc/blocks/story/view.css
  jetpack-9.3/_inc/blocks/story/view.rtl.css
  jetpack-9.3/extensions/blocks/story/player/style.scss
  jetpack-9.3/jetpack.php
  jetpack-9.3/modules/masterbar/admin-menu/class-admin-menu.php
  jetpack-9.3/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
  jetpack-9.3/readme.txt
  jetpack-9.3/vendor/autoload.php
  jetpack-9.3/vendor/autoload_packages.php
  jetpack-9.3/vendor/composer/InstalledVersions.php
  jetpack-9.3/vendor/composer/autoload_real.php
  jetpack-9.3/vendor/composer/autoload_static.php
  jetpack-9.3/vendor/composer/installed.php
  jetpack-9.3/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.3/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.3/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-9.3/vendor/jetpack-autoloader/class-container.php
  jetpack-9.3/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-9.3/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-9.3/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-9.3/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-9.3/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-9.3/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.3/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.3/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Needs Review

#1937 Renames ip-utils.php to class-iputils.php
  lib/proxy/class-iputils.php
Labels: [Status] Ready to Deploy

#1938 Add pre_option_jetpack_sync_settings_checksum_disable filter to allow for a killswitch for Jetpack Checksum functionality
  vip-jetpack/vip-jetpack.php
Labels: [Status] Ready to Deploy

#1941 Set Jetpack 9.3 as the default for all sites
  jetpack.php
Labels: [Status] Ready to Deploy

#1939 Update requires for the iputils
  lib/proxy/ip-forward.php
  tests/bootstrap.php
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#1942 Update Jetpack 9.3 to 9.3.1
  jetpack-9.3/3rd-party/class-domain-mapping.php
  jetpack-9.3/changelog.txt
  jetpack-9.3/jetpack.php
  jetpack-9.3/modules/seo-tools/jetpack-seo.php
  jetpack-9.3/readme.txt
  jetpack-9.3/vendor/autoload.php
  jetpack-9.3/vendor/autoload_packages.php
  jetpack-9.3/vendor/composer/InstalledVersions.php
  jetpack-9.3/vendor/composer/autoload_real.php
  jetpack-9.3/vendor/composer/autoload_static.php
  jetpack-9.3/vendor/composer/installed.php
  jetpack-9.3/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.3/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.3/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-9.3/vendor/jetpack-autoloader/class-container.php
  jetpack-9.3/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-9.3/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-9.3/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-9.3/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-9.3/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-9.3/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.3/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.3/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Ready to Deploy

#1943 Add attachment to indexable post types when protected content enabled
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Needs Review

#1934 Enables search index versioning self healing
  search/includes/classes/class-versioning.php
Labels: [Status] Ready to Deploy

#1944 Increase frequency of Site Details generation
  config/class-sync.php
Labels: [Status] Needs Review

#1947 Remove renamed ip-utils.php
  lib/proxy/ip-utils.php
Labels: [Status] Ready to Deploy

#1940 Adds changelog creation automation
  .circleci/config.yml
  bin/github-changelog.php
  composer.json
  composer.lock
Labels: [Status] Ready to Deploy

#1950 Clean up whitespace phpcs issues - class-versioning
  search/includes/classes/class-versioning.php
Labels: [Status] Ready to Deploy

#1954 Include the original ElasticSearch query and backtrace when logging errors
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy

#1953 Removed PR URLs from changelog examples and edited changelog checklist item to be for everyone
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#1956 Use the new jetpack-production repository for Jetpack subtrees
  bin/add-jetpack-subtree.sh
  bin/update-jetpack-subtree.sh
Labels: [Status] Ready to Deploy

#1955 Move Files ACL endpoint
  files/acl/acl.php
  files/acl/endpoint-check-file-acl.php
Labels: [Status] Ready to Deploy

#1948 Add Files ACL Restriction Functionality
  a8c-files.php
  files/acl/acl.php
  files/acl/endpoint-check-file-acl.php
  files/acl/restrict-all-files.php
  files/acl/restrict-unpublished-files.php
  tests/files/acl/test-acl.php
  tests/files/acl/test-restrict-all-files.php
  tests/files/acl/test-restrict-unpublished-files.php
Labels: [Status] Ready to Deploy

#1960 phpcs cleanup search health job
  search/includes/classes/class-health-job.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy, [Tag] Search

#1961 adds tag support
  bin/github-changelog.php
Labels: [Status] Ready to Deploy

#1962 Adds class-healthjob.php for renaming of class-health-job.php
  search/includes/classes/class-healthjob.php
Labels: [Status] Ready to Deploy, [Tag] Search

#1965 Allow skipping loading VaultPress
  vaultpress.php
Labels: [Status] Ready to Deploy
