Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-10, with the labels that each got.

#2459 Hooking Parsely plugin tweaks to init
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#2464 Update site details endpoint from /sitedetails to /site-details
  config/class-site-details-index.php
Labels: [Status] Ready to Deploy

#2457 Search: Health - Validate counts for terms and comments indexables
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#2465 Conditionally loading init action on wp-parsely
  wp-parsely.php
Labels: [Status] Needs Review, [Component] Parse.ly

#2467 Don't use global declaration on Parse.ly
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#2456 Fix the pre-push Git hook
  .husky/pre-push
  package.json
Labels: [Type] Bug, [Status] Ready to Deploy, [Component] Code Standards

#2473 Update phpcs.xml.dist
  phpcs.xml.dist
Labels: [Status] Ready to Deploy, [Type] Maintenance

#2458 Update JavaScript dependencies
  package-lock.json
  package.json
Labels: [Type] Maintenance

#2415 Fix phpcs issues for vip-init plugin
  000-vip-init.php
  config/class-site-details-index.php
  config/class-sync.php
  lib/class-apc-cache-interceptor.php
  lib/class-vip-encloseme-cleanup.php
  lib/class-vip-request-block.php
  lib/feature/class-feature.php
  lib/proxy/class-iputils.php
  lib/proxy/ip-forward.php
  lib/sms.php
  lib/statsd/class-statsd.php
  lib/sunrise/sunrise.php
  lib/utils/class-alerts.php
  lib/utils/class-context.php
  lib/wpcom-error-handler/wpcom-error-handler.php
  tests/lib/utils/context.php
Labels: [Status] Ready to Deploy, [Component] Code Standards
