Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-06, with the labels that each got.

#2175 Temporarily remove register_block_core_legacy_widget because it interferes with our tests
  tests/bootstrap.php
Labels: [Status] Needs Review

#2174 Adds safe reindexing support
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy

#2179 Make Jetpack 9.8 default
  jetpack.php
Labels: [Status] Needs Review

#2178 Stricter validation for URLs in Search Dev Tools
  search/search-dev-tools/search-dev-tools.php
  tests/search/test-search-dev-tools.php
Labels: [Component] Search, [Status] Ready to Deploy

#2160 Flush cache for page: also purge the AMP url
  vip-cache-manager/js/admin-bar.js
Labels: [Status] Ready to Deploy

#2183 Jetpack: update jetpack-9.4 to 9.4.2
  jetpack-9.4/modules/carousel/jetpack-carousel.php
  jetpack-9.4/readme.txt
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2184 Update Jetpack 9.1 to 9.1.1
  jetpack-9.1/modules/carousel/jetpack-carousel.php
  jetpack-9.1/readme.txt
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2167 Fix tests to make sure WPCOM_VIP_Cache_Manager doesn't interfere with other tests
  tests/bootstrap.php
  tests/test-cache-purge-term.php
  tests/test-vip-cache-manager.php
Labels: [Status] Ready to Deploy

#2165 Adds longer timeout to validate counts
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy

#2166 Featured Plugins Fix: Wait for images to load before calculating height
  vip-plugins/css/plugins-ui.css
  vip-plugins/js/plugins-ui.js
  vip-plugins/vip-plugins.php
Labels: [Status] Ready to Deploy

#2194 Update Jetpack 9.5 subtree to 9.5.3
  jetpack-9.5/modules/carousel/jetpack-carousel.php
  jetpack-9.5/readme.txt
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2195 Update Jetpack 9.6 subtree to 9.6.2
  jetpack-9.6/modules/carousel/jetpack-carousel.php
  jetpack-9.6/readme.txt
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2196 Update Jetpack 9.7 subtree to 9.7.1
  jetpack-9.7/modules/carousel/jetpack-carousel.php
  jetpack-9.7/readme.txt
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2192 ALLOPTIONS: Tweak the alert limits (increase warning to 1.5mb and critical to 4MB, set the desired interval of re-alerting to 30m
  alloptions-limit.php
Labels: [Status] Ready to Deploy

#1378 Cache Manager: Purge posts page
  tests/test-vip-cache-manager.php
  vip-cache-manager/vip-cache-manager.php
Labels: [Status] Ready to Deploy

#2199 Update Jetpack 9.8 to 9.8.1
  jetpack-9.8/CHANGELOG.md
  jetpack-9.8/_inc/blocks/editor-beta.asset.php
  jetpack-9.8/_inc/blocks/editor-beta.js
  jetpack-9.8/_inc/blocks/editor-experimental.asset.php
  jetpack-9.8/_inc/blocks/editor-experimental.js
  jetpack-9.8/_inc/blocks/editor.asset.php
  jetpack-9.8/_inc/blocks/editor.js
  jetpack-9.8/_inc/build/carousel/jetpack-carousel.min.js
  jetpack-9.8/composer.json
  jetpack-9.8/css/jetpack-rtl.css
  jetpack-9.8/css/jetpack.css
  jetpack-9.8/extensions/blocks/story/story.php
  jetpack-9.8/jetpack.php
  jetpack-9.8/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php
  jetpack-9.8/modules/carousel/jetpack-carousel.js
  jetpack-9.8/modules/related-posts/jetpack-related-posts.php
  jetpack-9.8/modules/related-posts/related-posts-rtl.css
  jetpack-9.8/modules/related-posts/related-posts.css
  jetpack-9.8/readme.txt
  jetpack-9.8/vendor/autoload.php
  jetpack-9.8/vendor/autoload_packages.php
  jetpack-9.8/vendor/composer/ClassLoader.php
  jetpack-9.8/vendor/composer/InstalledVersions.php
  jetpack-9.8/vendor/composer/autoload_files.php
  jetpack-9.8/vendor/composer/autoload_real.php
  jetpack-9.8/vendor/composer/autoload_static.php
  jetpack-9.8/vendor/composer/installed.php
  jetpack-9.8/vendor/composer/jetpack_autoload_classmap.php
  jetpack-9.8/vendor/composer/jetpack_autoload_filemap.php
  jetpack-9.8/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.8/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.8/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-9.8/vendor/jetpack-autoloader/class-container.php
  jetpack-9.8/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-9.8/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-9.8/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-9.8/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-9.8/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-9.8/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-9.8/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.8/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-9.8/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.8/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Component] Jetpack, [Status] Needs Review

#2197 Adding checks for Jetpack Autoconnection staged rollout
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2201 Enable Connection Pilot for all sites
  000-vip-init.php
  lib/feature/class-feature.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Do not deploy!

#2203 Ignoring Akismet and VaultPress dirs for Renovate bot
  renovate.json
Labels: dependencies

#2204 Adds confirm message
  search/includes/classes/commands/class-corecommand.php
Labels: [Component] Search, [Status] Ready to Deploy

#2208 Remove index removal
  search/includes/classes/queue/class-schema.php
Labels: [Status] Ready to Deploy

#2216 Search move inconsistency alerts
  search/includes/classes/class-healthjob.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#2217 Hide Akismet admin notices
  akismet.php
Labels: [Status] Ready to Deploy

#2205 Remove `$wp_admin_bar` argument
  blogpublic-notice.php
Labels: [Status] Ready to Deploy

#2209 Enable Search Dev Tools for 25% of sites and ALL non-prod sites
  000-vip-init.php
  lib/feature/class-feature.php
  tests/search/test-search-dev-tools.php
Labels: [Status] Ready to Deploy

#2206 Adding Akismet autoconnection
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2223 Forcing VIP user to perform Akismet autoconnect
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
Labels: [Component] Jetpack, [Status] Needs Review

#2207 Adding VaultPress autoconnection
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Component] VaultPress, [Status] Needs Review

#2221 Adds get settings subcommand
  search/includes/classes/commands/class-corecommand.php
Labels: [Component] Search, [Status] Ready to Deploy

#2224 Staged rollout of Connection Pilot and logs cleanup
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Needs Review

#2200 Improve security
  security.php
Labels: [Status] Has Feedback

#2237 Block using 403 http code as 410 has unintended cache implications
  lib/class-vip-request-block.php
Labels: [Status] Needs Review

#2227 Checking Jetpack Connection owner after Jetpack site is connected
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2228 Removing else linter warnings on vip-dashboard
  vip-dashboard/components/forms/sortable-list/index.jsx
Labels: [Status] Needs Review

#2218 Tweaking Connection Pilot cron job schedules
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2230 Upgrading to custom PHPUnit Docker image
  bin/phpunit-docker.sh
Labels: [Status] Ready to Deploy

#2238 Specify blocking only applies to origin requests
  lib/class-vip-request-block.php
Labels: [Status] Ready to Deploy

#2239 Indexables::factory may return a boolean FALSE if an indexable is not registered, which may result in Error: Uncaught exception 'Error'
  search/includes/classes/class-cache.php
Labels: [Component] Search, [Status] Ready to Deploy

#2057 Allow VIP File System uploads as email attachments
  vip-mail.php
Labels: [Status] Ready to Deploy

#2242 Add a temporary feature flag for VIP_PHPMailer until unit tests are added
  vip-mail.php
Labels: [Status] Ready to Deploy

#2244 Don't include the VIP_PHPMailer on WordPress < 5.5, add test coverage
  tests/test-vip-mail.php
  vip-mail.php
Labels: [Status] Ready to Deploy

#2219 Removing redundant Connection Pilot connection checks
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2250 Enable Jetpack CP reconnection filter by default
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Needs Review

#2251 Remove deadlocked jobs that are already queued
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Component] Search, [Status] Ready to Deploy

#2240 Skipping VaultPress reconnect if it's disabled
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] VaultPress, [Status] Ready to Deploy

#2229 Update validate content logic to correctly handle missing keys
  search/includes/classes/class-health.php
  tests/search/includes/classes/test-class-health.php
Labels: [Component] Search, [Status] Ready to Deploy

#1616 Two Factor: Better check for proxied Automattician
  two-factor.php
Labels: [Status] Ready to Deploy

#2202 Releasing Jetpack Connection Pilot by default to all sites
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Ready to Deploy
