Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-02, with the labels that each got.

#1957 adds cron job to detect inactive index-versions
  search/includes/classes/class-search.php
  search/includes/classes/class-versioningcleanupjob.php
  tests/search/includes/classes/test-class-versioningcleanupjob.php
  tests/search/test-class-search.php
Labels: [Status] Ready to Deploy, [Tag] Search

#1966 Fails circleCI pipeline on failure
  bin/github-changelog.php
Labels: [Status] Ready to Deploy

#1951 Update/search default meta whitelist
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Status] Has Feedback

#1968 Changes search healthjob's requires
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Component] Search, [Status] Ready to Deploy

#1969 remove renamed class-health-job.php
  search/includes/classes/class-health-job.php
Labels: [Component] Code Standards, [Component] Search

#1971 Set Jetpack 9.4 as the default version
  jetpack.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#1972 Always filter the jetpack_https_test transient to 1
  tests/test-vip-jetpack.php
  vip-jetpack/vip-jetpack.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#1973 Filter the fallback_no_verify_ssl_certs Jetpack Option to 0
  tests/admin-notice/test-admin-notice.php
  tests/bootstrap.php
  tests/test-vip-jetpack.php
  tests/vip-helpers/test-wpcom-vip-load-plugin.php
  vip-jetpack/vip-jetpack.php
Labels: [Component] Jetpack

#1970 Add VIP NotOptions Mitigation
  vip-helpers/vip-notoptions-mitigation.php
Labels: [Status] Ready to Deploy

#1963 Properly handle file paths with `sites/:id`
  files/acl/restrict-unpublished-files.php
  tests/files/acl/test-restrict-unpublished-files.php
Labels: [Component] Security, [Status] Ready to Deploy

#1974 Private Files: Always send X-Private header
  files/acl/acl.php
  tests/files/acl/test-acl.php
Labels: [Component] Security, [Status] Ready to Deploy

#1975 Private Files: Restrict cross-site file access
  files/acl/acl.php
  files/acl/endpoint-check-file-acl.php
  tests/files/acl/test-acl.php
Labels: [Component] Security, [Status] Ready to Deploy

#1976 Update/search skip validation if not indexed
  search/includes/classes/class-health.php
  search/includes/classes/class-healthjob.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-health.php
Labels: [Component] Search, [Status] Ready to Deploy

#1958 Fix a bug with use_block_editor_for_post filter in WP Core
  001-core.php
Labels: [Status] Ready to Deploy, [Type] Bug

#1981 Prevent invalid core query args
  001-core.php
Labels: [Status] Ready to Deploy

#1980 Private Files: PURGE attachment URLs on post update
  files/acl/acl.php
  files/acl/restrict-unpublished-files.php
  tests/files/acl/test-acl.php
  tests/files/acl/test-restrict-unpublished-files.php
Labels: [Component] File Access Control, [Status] Ready to Deploy

#1988 Search: Sanitize EP query for error logging
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Component] Search, [Status] Ready to Deploy

#1982 Add scheduled user-role backup and management CLI
  000-vip-init.php
  vip-helpers/class-vip-backup-user-role-cli.php
  vip-helpers/vip-notoptions-mitigation.php
Labels: [Status] Needs Review

#1991 Remove unnecessary hook on rest_api_init to schedule Search cron job
  search/includes/classes/queue/class-cron.php
Labels: [Component] Search, [Status] Ready to Deploy

#1597 Show notice if a non-prod site may be indexable
  blogpublic-notice.php
Labels: [Status] Ready to Deploy

#1989 Adds argument validations
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
Labels: [Component] Search, [Status] Ready to Deploy

#1996 Wrap blog public notices use of VIP_GO_APP_ENVIRONMENT in a defined check
  blogpublic-notice.php
Labels: [Status] Needs Review

#1995 Move WP_EP_DEBUG defining and EP debug bar panel loading to before dependencies are loaded
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Component] Search, [Status] Ready to Deploy

#1997 Update/phpcs class vip filesystem
  files/class-vip-filesystem.php
Labels: [Component] Code Standards, [Status] Ready to Deploy

#1994 Move requests variable definition higher in A8C_Files::purge_file_cache to prevent returning undefined variable
  a8c-files.php
Labels: [Status] Ready to Deploy

#1993 Switch `VIP_Request_Block::block_and_log()` to public visibility
  lib/class-vip-request-block.php
Labels: [Status] Ready to Deploy

#1978 Fix the potential race condition with notoptions
  misc.php
Labels: [Status] Ready to Deploy

#2001 Refresh Jetpack Connection Pilot (A Space Odyssey)
  vip-jetpack/connection-pilot/bin/partner-provision.sh
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Status] Needs Review

#2002 Feature lib updates: add usage examples, some basic PHP Doc and enable Jetpack connection Pilot
  lib/feature/class-feature.php
Labels: [Component] Jetpack, [Status] Ready to Deploy
