Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-03, with the labels that each got.

#2004 Search: Add result compression
  search/includes/classes/class-search.php
Labels: [Component] Search, [Status] Ready to Deploy

#1998 Fix incorrect limit return for wpcom_vip_top_posts_array
  vip-helpers/vip-stats.php
Labels: [Status] Ready to Deploy

#2010 Set Jetpack 9.5 as the default version for all VIP sites
  jetpack.php
Labels: [Component] Jetpack, [Status] Needs Review

#2011 Update Jetpack 9.5 to version 9.5.1
  jetpack-9.5/_inc/blocks/editor-beta.asset.php
  jetpack-9.5/_inc/blocks/editor-beta.js
  jetpack-9.5/_inc/blocks/editor-experimental.asset.php
  jetpack-9.5/_inc/blocks/editor-experimental.js
  jetpack-9.5/_inc/blocks/editor-no-post-editor.asset.php
  jetpack-9.5/_inc/blocks/editor-no-post-editor.js
  jetpack-9.5/_inc/blocks/editor.asset.php
  jetpack-9.5/_inc/blocks/editor.js
  jetpack-9.5/changelog.txt
  jetpack-9.5/functions.opengraph.php
  jetpack-9.5/jetpack.php
  jetpack-9.5/modules/subscriptions/views.php
  jetpack-9.5/readme.txt
Labels: [Component] Jetpack, [Status] Needs Review

#2012 Hotfix: jetpack-start WP CLI command compatibility with Jetpack 9.5
  jetpack-start/wp-cli-provision.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2017 Revise PR template to be inline with guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#2015 Fix the potential race condition with notoptions
  misc.php
Labels: [Status] Ready to Deploy

#2009 Akismet 4.1.9
  akismet.php
  akismet/akismet.php
  akismet/class.akismet.php
  akismet/readme.txt
Labels: [Status] Ready to Deploy

#2019 Ensure hosts not empty before randomly picking one
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Component] Search, [Status] Ready to Deploy

#2020 Add PHP version field to the site details data
  config/class-site-details-index.php
Labels: [Status] Ready to Deploy

#1985 Search: Add index settings monitoring
  lib/feature/class-feature.php
  search/includes/classes/class-health.php
  search/includes/classes/class-healthjob.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-health.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Component] Search, [Status] Ready to Deploy

#2024 Exclude basic file tests from core run
  bin/utils.sh
Labels: [Status] Ready to Deploy

#2016 Enforce strict username sanitization
  security.php
Labels: [Status] Needs Review, [Status] Needs Tests

#2030 Search: Enable index settings monitoring on all sites
  lib/feature/class-feature.php
  search/includes/classes/class-health.php
  search/includes/classes/class-healthjob.php
Labels: [Status] Ready to Deploy

#2023 Search: Add index setting automation
  lib/feature/class-feature.php
  search/includes/classes/class-health.php
  search/includes/classes/class-healthjob.php
  tests/search/includes/classes/test-class-health.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#2025 Site Details: Include plugins that are enabled sitewide
  config/class-site-details-index.php
  tests/config/test-site-details-index.php
Labels: [Component] Site Details, [Status] Ready to Deploy

#2032 Update Jetpack to 9.5.2
  jetpack-9.5/_inc/blocks/editor-beta.asset.php
  jetpack-9.5/_inc/blocks/editor-beta.js
  jetpack-9.5/_inc/blocks/editor-experimental.asset.php
  jetpack-9.5/_inc/blocks/editor-experimental.js
  jetpack-9.5/_inc/blocks/editor-no-post-editor.asset.php
  jetpack-9.5/_inc/blocks/editor-no-post-editor.js
  jetpack-9.5/_inc/blocks/editor.asset.php
  jetpack-9.5/_inc/blocks/editor.js
  jetpack-9.5/_inc/build/instant-search/jp-search-main.bundle.asset.php
  jetpack-9.5/_inc/build/instant-search/jp-search-main.bundle.js
  jetpack-9.5/_inc/build/instant-search/jp-search.chunk-3-653479f0260c1132b2bb.js
  jetpack-9.5/_inc/build/masterbar/admin-menu/admin-menu.min.js
  jetpack-9.5/changelog.txt
  jetpack-9.5/changelog/add-edit-css-appearance-menu-item
  jetpack-9.5/changelog/fix-admin-menu-migrate-submenu-hooks
  jetpack-9.5/changelog/fix-search-ie11-modal-summon
  jetpack-9.5/changelog/remove-admin-menu-links-manager
  jetpack-9.5/changelog/update-admin-menu-catchup
  jetpack-9.5/jetpack.php
  jetpack-9.5/modules/masterbar/admin-menu/admin-menu.css
  jetpack-9.5/modules/masterbar/admin-menu/admin-menu.js
  jetpack-9.5/modules/masterbar/admin-menu/class-admin-menu.php
  jetpack-9.5/modules/masterbar/admin-menu/class-atomic-admin-menu.php
  jetpack-9.5/modules/masterbar/admin-menu/class-jetpack-admin-menu.php
  jetpack-9.5/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
  jetpack-9.5/modules/photon-cdn/jetpack-manifest.php
  jetpack-9.5/readme.txt
  jetpack-9.5/vendor/composer/jetpack_autoload_classmap.php
Labels: [Status] Needs Review

#2033 Moves core tests to phph7.4
  .circleci/config.yml
Labels: [Status] Ready to Deploy

#2029 removing out of date to-do comment
  files/class-api-client.php
Labels: [Status] Ready to Deploy

#2027 PHPUnit: Add "name" attribute for "testsuite" element to avoid warnings
  phpunit-multisite.xml
  phpunit.xml
Labels: [Status] Ready to Deploy

#2028 Updates convertor CLI tool to fetch DB name from DB
  wp-cli/vip-go-convert-to-utf8mb4.php
Labels: [Status] Ready to Deploy

#2005 Merge 'add/local-vip-go-env-const'...
  000-debug/debug-mode.php
  debug-bar.php
Labels: [Feature] Sandboxen, [Status] Ready to Deploy

#2034 Ignore the bin and tests directories of object-cache dropin for deployment
  .deployignore
Labels: [Status] Ready to Deploy

#1990 Adds validate content lock
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-health.php
Labels: [Component] Search, [Status] Ready to Deploy

#2037 Adds validate content interruption recovery
  search/includes/classes/class-health.php
  tests/search/includes/classes/test-class-health.php
Labels: [Component] Search, [Status] Ready to Deploy

#2036 fixes intermediate_image_sizes_advanced param size
  files/class-image-sizes.php
Labels: [Status] Ready to Deploy

#2041 Search Cron - validate contents: Update alert text with site ID
  search/includes/classes/class-healthjob.php
Labels: [Component] Search

#2043 Extract sandbox/cli container detection to new Environment class
  lib/environment/class-environment.php
  tests/lib/environment/test-class-environment.php
Labels: [Status] Needs Review

#2026 Support suppression of alloptions size alerts
  alloptions-limit.php
  wp-cli/alloptions.php
Labels: [Status] Ready to Deploy

#2044 Add domain to site search columns to improve WP Admin site search results
  misc.php
Labels: [Status] Ready to Deploy

#2047 ALLOPTIONS limit alert/block - account for the fact that pecl-memcache client automagically compresses the values before sending it to the server
  alloptions-limit.php
Labels: [Status] Ready to Deploy

#2031 Search: Update index replica count
  search/includes/classes/class-search.php
  tests/search/test-class-search.php
Labels: [Component] Search

#2053 Search: Auto-heal index settings on 10% of sites
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2048 Increases the rollout of contents cron to 25p
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2054 Search: Enable index setting automation on 50% of sites
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2051 Limit Max Window Size
  search/includes/classes/class-health.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-health.php
  tests/search/test-class-search.php
Labels: [Component] Search, [Status] Ready to Deploy
