Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-07, with the labels that each got.

#2256 Fix ESLint issues in Search Dev Tools
  search/search-dev-tools/.babelrc.json
  search/search-dev-tools/.eslintrc.json
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
Labels: [Status] Needs Review

#2260 ignore babel config for deploy
  .deployignore
Labels: [Status] Needs Review

#2254 Search dev tools: address a potential fatal error 'Uncaught Error: Cannot use object of type WP_Error as array' when an underlying ES query has timed out
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/search-dev-tools.php
  search/search-dev-tools/src/components/query/index.js
Labels: [Status] Ready to Deploy

#2262 Search-dev-tools fix linting issues
  search/search-dev-tools/build/bundle.css
  search/search-dev-tools/build/bundle.fa5d1.esm.js
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/build/polyfills.6d557.esm.js
  search/search-dev-tools/build/polyfills.b41f8.esm.js
  search/search-dev-tools/src/components/app.js
  search/search-dev-tools/src/components/collapsible-list/index.js
  search/search-dev-tools/src/components/information-pane/index.js
  search/search-dev-tools/src/components/overlay/index.js
  search/search-dev-tools/src/components/query/index.js
  search/search-dev-tools/src/webpack-public-path.js
Labels: [Status] Needs Review

#2255 Allow to test all files with specific WP version
  README.md
  bin/phpunit-docker.sh
Labels: [Status] Ready to Deploy

#2272 Removing Connection Pilot legacy constants
  000-vip-init.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Status] Ready to Deploy

#2273 Upgrading Jetpack 9.9 branch to release
  jetpack-9.9/CHANGELOG.md
  jetpack-9.9/_inc/build/carousel/jetpack-carousel.min.js
  jetpack-9.9/composer.json
  jetpack-9.9/css/jetpack-rtl.css
  jetpack-9.9/css/jetpack.css
  jetpack-9.9/jetpack.php
  jetpack-9.9/json-endpoints/class.wpcom-json-api-update-site-logo-endpoint.php
  jetpack-9.9/modules/carousel/images/arrows-2x.png
  jetpack-9.9/modules/carousel/images/arrows.png
  jetpack-9.9/modules/carousel/jetpack-carousel-rtl.css
  jetpack-9.9/modules/carousel/jetpack-carousel.css
  jetpack-9.9/modules/carousel/jetpack-carousel.js
  jetpack-9.9/modules/carousel/jetpack-carousel.php
  jetpack-9.9/modules/photon-cdn/jetpack-manifest.php
  jetpack-9.9/modules/theme-tools/site-logo.php
  jetpack-9.9/modules/theme-tools/site-logo/css/site-logo-control-rtl.css
  jetpack-9.9/modules/theme-tools/site-logo/css/site-logo-control-rtl.min.css
  jetpack-9.9/modules/theme-tools/site-logo/css/site-logo-control.css
  jetpack-9.9/modules/theme-tools/site-logo/css/site-logo-control.min.css
  jetpack-9.9/modules/theme-tools/site-logo/inc/class-site-logo-control.php
  jetpack-9.9/modules/theme-tools/site-logo/inc/class-site-logo.php
  jetpack-9.9/modules/theme-tools/site-logo/inc/functions.php
  jetpack-9.9/modules/theme-tools/site-logo/js/site-logo-control.js
  jetpack-9.9/modules/theme-tools/site-logo/js/site-logo-control.min.js
  jetpack-9.9/modules/theme-tools/site-logo/js/site-logo.js
  jetpack-9.9/modules/theme-tools/site-logo/js/site-logo.min.js
  jetpack-9.9/modules/widgets/milestone/class-milestone-widget.php
  jetpack-9.9/readme.txt
  jetpack-9.9/sal/class.json-api-site-base.php
  jetpack-9.9/vendor/autoload.php
  jetpack-9.9/vendor/autoload_packages.php
  jetpack-9.9/vendor/automattic/jetpack-password-checker/LICENSE.txt
  jetpack-9.9/vendor/automattic/jetpack-password-checker/SECURITY.md
  jetpack-9.9/vendor/automattic/jetpack-sync/CHANGELOG.md
  jetpack-9.9/vendor/automattic/jetpack-sync/src/class-settings.php
  jetpack-9.9/vendor/automattic/jetpack-sync/src/replicastore/class-table-checksum.php
  jetpack-9.9/vendor/composer/InstalledVersions.php
  jetpack-9.9/vendor/composer/autoload_real.php
  jetpack-9.9/vendor/composer/autoload_static.php
  jetpack-9.9/vendor/composer/installed.json
  jetpack-9.9/vendor/composer/installed.php
  jetpack-9.9/vendor/composer/jetpack_autoload_classmap.php
  jetpack-9.9/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.9/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.9/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-9.9/vendor/jetpack-autoloader/class-container.php
  jetpack-9.9/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-9.9/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-9.9/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-9.9/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-9.9/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-9.9/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-9.9/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.9/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-9.9/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.9/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2259 Bump Search Dev Tools rollout to 50% of sites
  lib/feature/class-feature.php
Labels: [Component] Search, [Status] Blocked, [Status] Ready to Deploy

#2261 Switch recommended dev-env
  README.md
  search/search-dev-tools/README.md
Labels: [Status] Ready to Deploy

#2276 Replace "host" field by "http_host" in log2logstash messages
  logstash/class-logger.php
  tests/logstash/test-logger.php
Labels: [Status] Ready to Deploy

#2274 Making Jetpack 9.9 default
  jetpack.php
Labels: [Component] Jetpack, [Status] Do not deploy!, [Status] Ready to Deploy

#2278 Update Akismet to v4.1.10
  akismet.php
  akismet/_inc/akismet.js
  akismet/akismet.php
  akismet/class.akismet-widget.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/notice.php
Labels: [Status] Ready to Deploy

#2281 Remove duplicate prefix on failed Query Log
  search/includes/classes/class-search.php
Labels: [Component] Search, [Status] Needs Review

#2286 Don't run Connection Pilot on local environments
  000-vip-init.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2287 Fix non-existent notify_pilot function in Connection Pilot
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2263 Adds a CI pipeline for search-dev-tools
  .circleci/config.yml
Labels: [Status] Has Feedback, [Status] Needs Review

#2299 Disabling WebP images upload temporarily
  misc.php
Labels: [Status] Needs Review

#2294 Adding support for additional PHPUnit args
  bin/phpunit-docker.sh
Labels: [Status] Needs Review

#2303 Fix broken EP hook after EP upgrade
  search/includes/classes/class-versioning.php
Labels: [Component] Search, [Status] Ready to Deploy

#2306 Fix VIP stats functions when Jetpack stats module is disabled
  vip-helpers/vip-stats.php
Labels: [Component] Jetpack, [Status] Needs Review

#2302 Pre-set the `apikey` portion of empty `parsely` site options to `site_url` (if loaded)
  wp-parsely.php
Labels: [Status] Ready to Deploy
