Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-05, with the labels that each got.

#2090 Run search validate contents on all sites
  lib/feature/class-feature.php
  search/includes/classes/class-healthjob.php
Labels: [Component] Search, [Status] Needs Review

#2093 Bump Admin Password Verification to 25%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2088 Hide VaultPress onboarding prompts when not connected
  vaultpress.php
Labels: [Component] VaultPress, [Status] Ready to Deploy

#2089 Remove VaultPress from admin menu when not connected
  vaultpress.php
Labels: [Component] VaultPress, [Status] Ready to Deploy

#2091 Move out search settings health check/healing to dedicated cron job
  search/includes/classes/class-healthjob.php
  search/includes/classes/class-search.php
  search/includes/classes/class-settingshealthjob.php
  tests/search/includes/classes/test-class-healthjob.php
  tests/search/includes/classes/test-class-settingshealthjob.php
Labels: [Component] Search, [Status] Has Feedback

#2092 Remove Akismet from admin menu when not connected
  akismet.php
Labels: [Status] Needs Review

#2095 Add Jetpack Connect Notice
  vip-jetpack/vip-jetpack.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2096 Don't try to add Jetpack connect menu if Jetpack is not active
  vip-jetpack/vip-jetpack.php
Labels: [Status] Ready to Deploy

#2106 Updating VIP dashboard dependencies to latest minor
  vip-dashboard/assets/css/style.css
  vip-dashboard/assets/js/vip-dashboard.js
  vip-dashboard/package-lock.json
  vip-dashboard/package.json
Labels: [Status] Needs Review

#2107 adds index name to logs
  search/includes/classes/class-health.php
  search/includes/classes/class-healthjob.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#2097 Adding CI test cases with disabled Jetpack
  .circleci/config.yml
  tests/test-vip-jetpack.php
Labels: [Status] Ready to Deploy

#2108 Update default JetPack vesion from 9.6 to 9.7
  jetpack.php
Labels: [Component] Jetpack, [Status] Blocked, [Status] Needs Review

#2111 Use Jetpack's offline mode in Connection Pilot
  vip-jetpack/connection-pilot/class-jetpack-connection-controls.php
Labels: [Status] Ready to Deploy

#2112 don't validate count without index
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-health.php
Labels: [Status] Ready to Deploy

#2110 Don't try to update the index settings if the setting key is not in the list of INDEX_SETTINGS_HEALTH_AUTO_HEAL_KEYS
  search/includes/classes/class-settingshealthjob.php
  tests/search/includes/classes/test-class-settingshealthjob.php
Labels: [Component] Search, [Status] Ready to Deploy

#2109 File Service: implement handling of the read-only mode for core upload methods
  files/class-api-client.php
  tests/files/test-api-client.php
Labels: [Status] Ready to Deploy

#2126 Remove VIP Dashboard widgets and stats dead code
  vip-dashboard/assets/css/style.css
  vip-dashboard/assets/js/vip-dashboard.js
  vip-dashboard/components/count/index.jsx
  vip-dashboard/components/stats-charts/index.jsx
  vip-dashboard/components/stats-charts/style.scss
  vip-dashboard/components/stats-numbers/index.jsx
  vip-dashboard/components/stats-numbers/style.scss
  vip-dashboard/components/stats/index.jsx
  vip-dashboard/components/stats/style.scss
  vip-dashboard/components/style.scss
  vip-dashboard/components/vip-dashboard.jsx
  vip-dashboard/components/widget-editorial/index.jsx
  vip-dashboard/components/widget-editorial/style.scss
  vip-dashboard/components/widget-promo/index.jsx
  vip-dashboard/components/widget-promo/style.scss
  vip-dashboard/package-lock.json
  vip-dashboard/package.json
Labels: [Status] Ready to Deploy

#2125 Search: Don't try to validate index settings for index versions that don't exist
  search/includes/classes/class-health.php
  tests/search/includes/classes/test-class-health.php
Labels: [Status] Ready to Deploy

#2094 Search Dev Tools
  search/search-dev-tools/.eslintrc.json
  search/search-dev-tools/.gitignore
  search/search-dev-tools/README.md
  search/search-dev-tools/build/assets/close.svg
  search/search-dev-tools/build/assets/favicon.ico
  search/search-dev-tools/build/assets/icon.png
  search/search-dev-tools/build/assets/lg.svg
  search/search-dev-tools/build/assets/minus.svg
  search/search-dev-tools/build/assets/plus.svg
  search/search-dev-tools/build/assets/wpvip.svg
  search/search-dev-tools/build/bundle.css
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/build/favicon.ico
  search/search-dev-tools/build/polyfills.b41f8.esm.js
  search/search-dev-tools/build/polyfills.js
  search/search-dev-tools/package.json
  search/search-dev-tools/preact.config.js
  search/search-dev-tools/search-dev-tools.php
  search/search-dev-tools/src/assets/close.svg
  search/search-dev-tools/src/assets/favicon.ico
  search/search-dev-tools/src/assets/icon.png
  search/search-dev-tools/src/assets/lg.svg
  search/search-dev-tools/src/assets/minus.svg
  search/search-dev-tools/src/assets/plus.svg
  search/search-dev-tools/src/assets/wpvip.svg
  search/search-dev-tools/src/components/app.js
  search/search-dev-tools/src/components/collapsible-list/index.js
  search/search-dev-tools/src/components/collapsible-list/style.scss
  search/search-dev-tools/src/components/information-pane/index.js
  search/search-dev-tools/src/components/information-pane/style.scss
  search/search-dev-tools/src/components/overlay/index.js
  search/search-dev-tools/src/components/overlay/style.scss
  search/search-dev-tools/src/components/query/index.js
  search/search-dev-tools/src/components/query/style.scss
  search/search-dev-tools/src/components/style.scss
  search/search-dev-tools/src/context.js
  search/search-dev-tools/src/index.js
  search/search-dev-tools/src/manifest.json
  search/search-dev-tools/src/style/mixins.scss
  search/search-dev-tools/src/style/style.scss
  search/search-dev-tools/src/style/vars.scss
  search/search-dev-tools/src/template.html
  search/search-dev-tools/src/utils.js
  search/search-dev-tools/src/webpack-public-path.js
  search/search.php
Labels: [Component] Search, [Status] Ready to Deploy

#2132 Add search-dev-tools related records to .deployignore
  .deployignore
Labels: [Status] Needs Review

#2130 Roll out require current password to all sites
  lib/feature/class-feature.php
  security.php
Labels: [Status] Ready to Deploy

#2129 Removing Chart JS and bumping version
  vip-dashboard.php
  vip-dashboard/assets/js/vip-dashboard.js
  vip-dashboard/package-lock.json
  vip-dashboard/package.json
  vip-dashboard/vip-dashboard.php
Labels: [Status] Needs Review

#2133 Search Dev Tools: address some edge cases
  search/search-dev-tools/build/bundle.css
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package.json
  search/search-dev-tools/src/components/query/style.scss
  search/search.php
Labels: [Component] Search, [Status] Needs Review

#2140 PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#2142 Not loading VaultPress when Jetpack is disabled
  vaultpress.php
Labels: [Component] VaultPress, [Status] Needs Review

#2146 Hotfixes for Search Dev Tools
  search/search-dev-tools/build/bundle.css
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
  search/search-dev-tools/search-dev-tools.php
  search/search-dev-tools/src/components/overlay/style.scss
  search/search-dev-tools/src/components/query/index.js
  search/search-dev-tools/src/components/query/style.scss
  search/search-dev-tools/src/style/prism.scss
Labels: [Component] Search, [Status] Ready to Deploy

#2145 Not loading Akismet when Jetpack is disabled
  akismet.php
Labels: [Status] Ready to Deploy

#2143 Upgrading to VaultPress 2.1.4
  vaultpress.php
  vaultpress/composer.json
  vaultpress/readme.txt
  vaultpress/vaultpress.php
  vaultpress/vendor/autoload.php
  vaultpress/vendor/autoload_functions.php
  vaultpress/vendor/autoload_packages.php
  vaultpress/vendor/automattic/jetpack-autoloader/README.md
  vaultpress/vendor/automattic/jetpack-autoloader/composer.json
  vaultpress/vendor/automattic/jetpack-autoloader/src/AutoloadGenerator.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/CustomAutoloaderPlugin.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/autoload.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/class-autoloader-handler.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/class-classes-handler.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/class-files-handler.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/class-plugins-handler.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/class-version-selector.php
  vaultpress/vendor/automattic/jetpack-autoloader/src/functions.php
  vaultpress/vendor/class-autoloader-handler.php
  vaultpress/vendor/class-classes-handler.php
  vaultpress/vendor/class-files-handler.php
  vaultpress/vendor/class-plugins-handler.php
  vaultpress/vendor/class-version-selector.php
  vaultpress/vendor/composer/autoload_classmap_package.php
  vaultpress/vendor/composer/autoload_files_package.php
  vaultpress/vendor/composer/autoload_real.php
  vaultpress/vendor/composer/autoload_static.php
  vaultpress/vendor/composer/installed.json
Labels: [Status] Ready to Deploy

#2141 Fix imports when Jetpack is disabled
  vip-helpers/vip-migrations.php
Labels: [Component] Jetpack, [Status] Needs Review

#2149 update comment docs
  rewrite-rules-inspector.php
Labels: [Status] Ready to Deploy

#2134 Update/ensure index
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-cache.php
  tests/search/includes/classes/test-class-healthjob.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/includes/classes/test-class-search.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Ready to Deploy

#2151 ALLOPTIONS handling improvements
  alloptions-limit.php
Labels: [Status] Ready to Deploy

#2150 Loading VIP Jetpack conditionally and hiding more messaging
  jetpack.php
  vip-jetpack/vip-jetpack.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2159 Search Dev Tools compatibility fixes and permission restrictions
  search/includes/classes/class-search.php
  search/search-dev-tools/search-dev-tools.php
Labels: [Status] Needs Review

#2157 Deadlock Job Cleanup Updateup
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
Labels: [Status] Needs Review

#2123 Admin Notice: add Expression_Condition, add support for WP Core classes, add a way to add notices at various stages of exectuion
  admin-notice/admin-notice.php
  admin-notice/class-admin-notice.php
  admin-notice/conditions/class-expression-condition.php
Labels: [Status] Ready to Deploy

#2119 Tweak Jetpack Connection Pilot to autoconnect
  000-vip-init.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Component] Jetpack

#2162 Skip confirm
  search/includes/classes/commands/class-versioncommand.php
Labels: [Component] Search, [Status] Ready to Deploy

#2164 Update/add index name
  search/includes/classes/class-health.php
Labels: [Status] Ready to Deploy
