Repository Automattic/vip-go-mu-plugins, pull requests merged in 2021-04, with the labels that each got.

#2058 Add new subsite wp-blogs-update CLI command
  wp-cli/class-vip-subsites-cli-command.php
Labels: [Status] Ready to Deploy

#2059 Search: Enable auto index setting updating on all sites
  lib/feature/class-feature.php
  search/includes/classes/class-healthjob.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Status] Ready to Deploy

#2061 Cut down on the amount of examples for the PR template to make it less verbose
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Deployed to production

#2062 Remove CircleCI php7.3-build-* jobs
  .circleci/config.yml
Labels: [Status] Deployed to production

#2063 Update Jetpack 9.6 to the final release
  jetpack-9.6/CHANGELOG.md
  jetpack-9.6/_inc/blocks/editor-beta.asset.php
  jetpack-9.6/_inc/blocks/editor-beta.js
  jetpack-9.6/_inc/blocks/editor-experimental.asset.php
  jetpack-9.6/_inc/blocks/editor-experimental.js
  jetpack-9.6/_inc/blocks/editor-no-post-editor.asset.php
  jetpack-9.6/_inc/blocks/editor-no-post-editor.js
  jetpack-9.6/_inc/blocks/editor.asset.php
  jetpack-9.6/_inc/blocks/editor.js
  jetpack-9.6/_inc/lib/admin-pages/class.jetpack-admin-page.php
  jetpack-9.6/jetpack.php
  jetpack-9.6/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php
  jetpack-9.6/modules/masterbar/admin-color-schemes/class-admin-color-schemes.php
  jetpack-9.6/modules/masterbar/admin-menu/class-admin-menu.php
  jetpack-9.6/modules/masterbar/admin-menu/class-atomic-admin-menu.php
  jetpack-9.6/modules/masterbar/admin-menu/class-base-admin-menu.php
  jetpack-9.6/modules/masterbar/admin-menu/class-wpcom-admin-menu.php
  jetpack-9.6/modules/search/customize-controls/customize-controls.js
  jetpack-9.6/readme.txt
  jetpack-9.6/vendor/composer/jetpack_autoload_classmap.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2064 Stepwise disabling of Gutenberg Ramp plugin: 45%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2066 Set Jetpack 9.6 as the default version for all VIP sites
  jetpack.php
Labels: [Component] Jetpack, [Status] Ready to Deploy

#2069 Stepwise disabling of Gutenberg Ramp plugin: 70%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2071 Instruction
  search/docs/onboarding-migrations.md
Labels: [Status] Needs Review

#2067 Require current password when changing it
  lib/feature/class-feature.php
  security.php
  security/js/password.js
  security/password.php
  tests/security/test-password.php
Labels: [Status] Ready to Deploy

#2046 Disable search if we don't have ES connectivity
  000-vip-init.php
  search/includes/classes/class-search.php
  search/search.php
  tests/search/test-class-search.php
Labels: [Component] Search

#2073 Update/failing test fix
  README.md
  bin/utils.sh
Labels: [Status] Ready to Deploy

#2074 update/bump_self-healing-to-50
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#2070 Handle error response codes in Alerts
  lib/utils/class-alerts.php
  tests/lib/utils/test-alerts.php
Labels: [Status] Ready to Deploy

#2080 Support for mutiple IPs in HTTP_X_FORWARDED_FOR
  lib/class-vip-request-block.php
  tests/lib/test-vip-request-block.php
Labels: [Status] Ready to Deploy

#2085 Avoid deploying some Jetpack files that throw linting errors
  .deployignore
Labels: [Status] Needs Review

#2086 Bump package-lock.json dependencies on vip-dashboard
  vip-dashboard.php
  vip-dashboard/.nvmrc
  vip-dashboard/assets/css/style.css
  vip-dashboard/assets/js/vip-dashboard.js
  vip-dashboard/package-lock.json
  vip-dashboard/package.json
Labels: [Status] Ready to Deploy

#2081 Search: Add AMS to the list of ALLOWED_DATACENTERS
  search/includes/classes/class-search.php
Labels: [Component] Search, [Status] Ready to Deploy

#2087 Update/jetpack 9.7 beta 2
  jetpack-9.7/CHANGELOG.md
  jetpack-9.7/_inc/build/admin.asset.php
  jetpack-9.7/_inc/build/admin.css
  jetpack-9.7/_inc/build/admin.js
  jetpack-9.7/_inc/build/admin.rtl.css
  jetpack-9.7/composer.json
  jetpack-9.7/jetpack.php
  jetpack-9.7/vendor/autoload.php
  jetpack-9.7/vendor/autoload_packages.php
  jetpack-9.7/vendor/automattic/jetpack-password-checker/vendor/autoload.php
  jetpack-9.7/vendor/automattic/jetpack-password-checker/vendor/composer/InstalledVersions.php
  jetpack-9.7/vendor/automattic/jetpack-password-checker/vendor/composer/autoload_real.php
  jetpack-9.7/vendor/automattic/jetpack-password-checker/vendor/composer/autoload_static.php
  jetpack-9.7/vendor/composer/InstalledVersions.php
  jetpack-9.7/vendor/composer/autoload_real.php
  jetpack-9.7/vendor/composer/autoload_static.php
  jetpack-9.7/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-9.7/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-9.7/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-9.7/vendor/jetpack-autoloader/class-container.php
  jetpack-9.7/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-9.7/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-9.7/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-9.7/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-9.7/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-9.7/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-9.7/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-9.7/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-9.7/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-9.7/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Ready to Deploy
