Repository Automattic/vip-go-mu-plugins, pull requests merged in 2022-08, with the labels that each got.

#3452 Update Search Dev Tools dependencies
  search/search-dev-tools/package-lock.json
Labels: [Status] Needs Review, dependencies, [Status] No files to Deploy, javascript

#3454 Search: Roll out ES global timeout to 50%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy, [Component] Search

#3455 Search: Roll out filter_ep_enable_do_weighting to 50% of production
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy, [Component] Search

#3459 Update Jetpack 11.2 to release
  jetpack-11.2/CHANGELOG.md
  jetpack-11.2/composer.json
  jetpack-11.2/jetpack.php
  jetpack-11.2/jetpack_vendor/i18n-map.php
  jetpack-11.2/modules/sharedaddy/sharing-service.php
  jetpack-11.2/readme.txt
  jetpack-11.2/vendor/autoload.php
  jetpack-11.2/vendor/autoload_packages.php
  jetpack-11.2/vendor/composer/autoload_real.php
  jetpack-11.2/vendor/composer/autoload_static.php
  jetpack-11.2/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-11.2/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-11.2/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-container.php
  jetpack-11.2/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-11.2/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-11.2/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-11.2/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-11.2/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-11.2/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-11.2/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3461 Change debug_bar_panels filter priority
  debug-bar.php
Labels: [Status] Ready to Deploy

#3463 Update/jetpack 11.2 release
  jetpack-11.2/CHANGELOG.md
  jetpack-11.2/composer.json
  jetpack-11.2/jetpack.php
  jetpack-11.2/jetpack_vendor/i18n-map.php
  jetpack-11.2/modules/sharedaddy/sharing-service.php
  jetpack-11.2/readme.txt
  jetpack-11.2/vendor/autoload.php
  jetpack-11.2/vendor/autoload_packages.php
  jetpack-11.2/vendor/composer/autoload_real.php
  jetpack-11.2/vendor/composer/autoload_static.php
  jetpack-11.2/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-11.2/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-11.2/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-container.php
  jetpack-11.2/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-11.2/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-11.2/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-11.2/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-11.2/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-11.2/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-11.2/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-11.2/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3453 [CANTINA-889] Change the way the collectors are loaded
  prometheus.php
  prometheus/inc/class-collectorinterface.php
  prometheus/inc/class-plugin.php
  tests/prometheus/class-plugin-helper.php
  tests/prometheus/test-prometheus.php
  z-client-mu-plugins.php
Labels: [Status] Ready to Deploy

#3468 Fix fatal "in_array(): Argument #2 ($haystack) must be of type array, null given"
  vip-helpers/sandbox.php
Labels: [Status] Ready to Deploy

#3469 Rename vipgo_mu_plugins_loaded to vip_mu_plugins_loaded
  prometheus.php
  prometheus/inc/class-plugin.php
  tests/prometheus/test-prometheus.php
  z-client-mu-plugins.php
Labels: [Status] Needs Review, [Type] Maintenance

#3470 Add vip_prometheus_loaded hook
  prometheus/inc/class-plugin.php
Labels: [Status] Needs Review, [Type] Maintenance

#3473 Jetpack 11.2 default
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3477 Production release v20220408.2 (Jetpack)
  jetpack.php
Labels: [Status] Ready to Deploy

#3478 Staging release v20220804.1 (Jetpack)
  jetpack.php
Labels: [Status] Ready to Deploy

#3476 Bad code... Bad code everywhere...
  prometheus/inc/class-plugin.php
Labels: [Status] Ready to Deploy, [Type] Maintenance

#3480 Fix CVE-2022-2596
  bin/package-lock.json
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3479 Search: Roll out ES global timeout to 75%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy, [Component] Search

#3482 Search: Roll out filter_ep_enable_do_weighting to 75%
  lib/feature/class-feature.php
Labels: [Status] Needs Review, [Component] Search

#3487 Remove 5.6 from test matrix
  .github/workflows/ci.yml
Labels: [Component] Tests, [Status] No files to Deploy

#3481 Lockout Plugin: Add `VIP_ACCOUNT_STATUS` constant to display notice/lock site.
  security/class-lockout.php
Labels: [Status] Ready to Deploy, [Component] Security

#3489 [CANTINA-889] Add post stats collector
  prometheus-collectors/class-post-stats-collector.php
  prometheus.php
Labels: [Status] Ready to Deploy

#3488 [CANTINA-889] Add ES Prometheus Collector
  search/includes/classes/class-prometheus-collector.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-cache.php
  tests/search/includes/classes/test-class-search.php
  tests/search/includes/classes/test-class-settingshealthjob.php
Labels: [Status] Ready to Deploy, [Component] Search

#3490 Debug bar: Change to earlier hook to utilize remote request logging
  debug-bar.php
Labels: [Status] Ready to Deploy

#3496 Search: Fully roll out filter_ep_enable_do_weighting
  lib/feature/class-feature.php
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy, [Component] Search

#3497 Search: Fully roll out ES global timeout
  lib/feature/class-feature.php
  search/includes/classes/class-search.php
Labels: [Status] Needs Review, [Component] Search

#3502 Open the vip_files_acl_file_visibility filter
  files/acl/endpoint-check-file-acl.php
Labels: [Status] Ready to Deploy

#3498 Removed unprefixed environment variables (Once more; with feeling!)
  lib/environment/class-environment.php
  tests/lib/environment/test-class-environment.php
  tests/lib/helpers/test-environment.php
Labels: [Status] Ready to Deploy

#3504 VIP Support: Add more validation checks and account for existing user with different e-mail
  tests/vip-support/test-user.php
  vip-support/class-vip-support-cli.php
  vip-support/class-vip-support-user.php
Labels: [Status] Ready to Deploy

#3508 VIP Support: Remove vip_support from editable_roles for users without the vip_support role
  tests/vip-support/test-role.php
  vip-support/class-vip-support-role.php
Labels: [Status] Ready to Deploy

#3515 GH-2358: respect WPMU_PLUGIN_DIR/WPMU_PLUGIN_URL
  lib/sunrise/sunrise.php
  logstash/class-logger.php
  vip-jetpack/jetpack-mandatory.php
Labels: [Type] Enhancement, [Status] Ready to Deploy

#3499 Update jetpack_is_mobile() to account for X-Mobile-Class header
  lib/feature/class-feature.php
  tests/test-vip-jetpack.php
  vip-jetpack/vip-jetpack.php
Labels: [Status] Needs Review, [Component] Jetpack

#3503 Add Jetpack loading fallback
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3517 Tests: Add more testing to WP_Filesystem_VIP_Test
  files/class-wp-filesystem-vip.php
  tests/files/test-wp-filesystem-vip.php
  tests/mock-constants.php
Labels: [Component] Tests

#3521 CI: Remove dotfiles, XML, bin and tests folder for built repo
  .github/workflows/deploy.yml
Labels: [Status] Needs Review, [Status] No files to Deploy

#3522 Misc: Move priority up for _vip_filter_rest_url_for_ssl()
  misc.php
Labels: [Status] Ready to Deploy

#3524 Clean up mocked constants in test-class-healthjob.php
  tests/search/includes/classes/test-class-healthjob.php
Labels: [Type] Bug, [Status] Needs Review, [Component] Tests, [Status] No files to Deploy

#3523 Show where the constant was defined previously
  tests/mock-constants.php
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#3525 Remove preact-habitat
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
  search/search-dev-tools/src/index.js
Labels: [Status] Ready to Deploy, [Component] Search

#3529 Use deterministic test order for coverage generation
  .github/actions/run-wp-tests/action.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#3526 GH-1066: do not override SMTP server if it has already been set
  tests/test-vip-mail.php
  vip-mail.php
Labels: [Status] Ready to Deploy

#3537 Update e2e eslintrc for breaking changes in @automattic/eslint-plugin-wpvip
  __tests__/e2e/.eslintrc.js
  __tests__/e2e/lib/global-setup.ts
Labels: [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#3531 Search: Change default search character length limit to 80
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-search.php
Labels: [Status] Ready to Deploy, [Component] Search

#3530 Search: Add logging when content validation cron is kicked off
  search/includes/classes/class-healthjob.php
Labels: [Status] Ready to Deploy, [Component] Search

#3538 Add eslint-config-preact and fix found issues
  package-lock.json
  package.json
  search/search-dev-tools/.eslintrc.json
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
  search/search-dev-tools/src/components/app.js
  search/search-dev-tools/src/components/overlay/index.js
  search/search-dev-tools/src/components/query/index.js
  search/search-dev-tools/webpack.config.js
Labels: [Status] Ready to Deploy, [Type] Maintenance

#3527 Drop WP 5.5 checks in VIP Mail
  tests/test-vip-mail.php
  vip-mail.php
Labels: [Status] Ready to Deploy, [Type] Maintenance

#3541 Prometheus: Wrap each class in `file_exists()` to ensure no race conditions occur during deploys
  prometheus.php
Labels: [Status] Ready to Deploy

#3546 GH-1297: Add link to General Ticket Guidelines
  vip-dashboard/components/widget-contact.php
Labels: [Status] Needs Review

#3547 Fix phpunit.xml
  phpunit.xml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3548 Fix outdated URL in Contact support form
  vip-dashboard/components/widget-contact.php
Labels: [Status] Ready to Deploy

#3549 Roll out jetpack_is_mobile() changes to 25%
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy

#3550 Fix Contact Form URL for ticket guidelines
  vip-dashboard/components/widget-contact.php
Labels: [Status] Ready to Deploy

#3543 Adjust VIP Jetpack loader to safe-guard against an edge-case where Jetpack is present in active_plugins
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3561 CANTINA-903: add workarounds for Yoast SEO
  000-pre-vip-config/requires.php
  lib/helpers/php-compat.php
  tests/bootstrap.php
  tests/vip-helpers/test-vip-roles.php
  vip-helpers/vip-roles.php
Labels: [Status] Ready to Deploy

#3570 Load polyfills from vip-init
  000-pre-vip-config/requires.php
  000-vip-init.php
Labels: [Type] Bug, [Status] In Progress

#3573 VIP_Files_CLI_Command: Use vip_inmemory_cleanup over deprecated stop_the_insanity
  wp-cli/vip-filesystem.php
Labels: [Status] Ready to Deploy

#3574 Fix fatal error when Jetpack network active
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3579 Roll out filter pre_jetpack_is_mobile to 50% of production sites, which accounts for X-Mobile-Class header in jetpack_is_mobile()
  jetpack.php
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3581 Debug Bar: Fix fatal "Cannot declare class Debug_Bar, because the name is already in use"
  debug-bar.php
Labels: [Status] Ready to Deploy

#3587 Update E2E tests
  __tests__/e2e/specs/searchdevtools.spec.ts
Labels: [Status] Needs Review, [Component] Tests, [Status] No files to Deploy

#3589 Staging release: v20220831.0
  .github/actions/run-wp-tests/action.yml
  .github/workflows/codeql-analysis.yml
  000-vip-init.php
  __tests__/e2e/specs/searchdevtools.spec.ts
  composer.json
  composer.lock
  debug-bar.php
  jetpack.php
  lib/feature/class-feature.php
  lib/helpers/php-compat.php
  package-lock.json
  package.json
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
  tests/bootstrap.php
  tests/vip-helpers/test-vip-roles.php
  vip-helpers/vip-roles.php
  wp-cli/vip-filesystem.php
Labels: [Status] Needs Review

#3431 AI-16: Add ability to shutdown site when overdue
  000-vip-init.php
  errors/site-shutdown.html
  lib/utils/class-context.php
  tests/lib/utils/context.php
Labels: [Status] Ready to Deploy

#3594 CI: Remove unused mark-production-changelog.js and related files
  bin/mark-production-changelog.js
  bin/package-lock.json
  bin/package.json
Labels: [Status] No files to Deploy
