Repository Automattic/vip-go-mu-plugins, pull requests merged in 2022-04, with the labels that each got.

#3034 Updating Parse.ly 3.2 branch to 3.2.1
  wp-parsely-3.2/README.md
  wp-parsely-3.2/src/RemoteAPI/class-cached-proxy.php
  wp-parsely-3.2/src/RemoteAPI/class-wordpress-cache.php
  wp-parsely-3.2/wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#3032 Setting Parse.ly 3.2 as the default version
  .github/workflows/parsely.yml
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#3035 Fix update-jetpack-subtree.sh to just remove and add instead
  bin/update-jetpack-subtree.sh
Labels: [Status] Needs Review, [Status] No files to Deploy

#3031 Search: Do not alert if index is in midst of being re-built
  search/includes/classes/class-settingshealthjob.php
Labels: [Component] Search

#2975 ci: update allowed endpoints in e2e.yml workflow
  .github/workflows/e2e.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#3037 Search: Fixed bug when indexing a multisites with over 100 sites in batch mode, a false error of site not existing is returned.
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Needs Review, [Component] Search

#3038 Update Jetpack 10.8-beta2 to 10.8 release
  jetpack-10.8/CHANGELOG.md
  jetpack-10.8/composer.json
  jetpack-10.8/jetpack.php
  jetpack-10.8/jetpack_vendor/i18n-map.php
  jetpack-10.8/readme.txt
  jetpack-10.8/vendor/autoload.php
  jetpack-10.8/vendor/autoload_packages.php
  jetpack-10.8/vendor/composer/autoload_real.php
  jetpack-10.8/vendor/composer/autoload_static.php
  jetpack-10.8/vendor/composer/jetpack_autoload_classmap.php
  jetpack-10.8/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-10.8/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-10.8/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-10.8/vendor/jetpack-autoloader/class-container.php
  jetpack-10.8/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-10.8/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-10.8/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-10.8/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-10.8/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-10.8/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-10.8/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-10.8/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-10.8/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-10.8/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Status] Deployed to staging, [Component] Jetpack

#3040 Add hp=vip to kv for stats pixel
  stats.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3045 GH-2980: make sure `wpcom_vip_override_role_caps()` persists capabilities
  tests/vip-helpers/test-vip-roles.php
  vip-helpers/vip-roles.php
Labels: [Type] Bug, [Status] Ready to Deploy

#3042 Prevent the introduction of known vulnerabilities into the code
  .github/workflows/dependency-review.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#3049 Pin digests for GitHub Actions
  renovate.json
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3058 Update npm dependencies
  package-lock.json
  package.json
Labels: [Status] Needs Review, dependencies, [Status] No files to Deploy

#3060 Remove `renovate.json`
  renovate.json
Labels: dependencies, [Status] No files to Deploy

#3065 Configure Dependabot
  .github/dependabot.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3077 Search: Add fallback elasticsearch version
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy, [Component] Search

#3082 Search: Extend Elasticsearch info cache expiration
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy, [Component] Search

#3083 Search: Throw error when delete-index command is attempted to be used
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#3084 Pin action versions in dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3088 Add CodeQL scan workflow
  .github/codeql-config.yml
  .github/workflows/codeql-analysis.yml
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/src/components/query/index.js
Labels: [Status] Ready to Deploy, [Type] Maintenance

#3087 Secure Dependency Review workflow
  .github/workflows/dependency-review.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#3078 Show plugin update notices
  codebase-manager.php
  codebase-manager/codebase-manager.php
  codebase-manager/plugins/plugin.php
  codebase-manager/plugins/plugins-manager.php
Labels: [Status] Ready to Deploy

#3101 copy() returns true for non-existing files
  files/class-vip-filesystem-stream-wrapper.php
  tests/files/test-vip-filesystem-stream-wrapper.php
Labels: [Type] Bug, [Status] Needs Review

#3102 GH-3092: PHP 8 compat: offset must be contained in haystack for strpos()
  files/class-vip-filesystem.php
Labels: [Type] Bug, PHP Compatibility

#3103 Search: Do not alert on backfill of ep_feature_settings option
  search/includes/functions/utils.php
Labels: [Status] Ready to Deploy, [Component] Search

#3105 Update Jetpack 10.9-beta to 10.9-beta2
  jetpack-10.9/CHANGELOG.md
  jetpack-10.9/composer.json
  jetpack-10.9/jetpack.php
  jetpack-10.9/jetpack_vendor/automattic/jetpack-connection/CHANGELOG.md
  jetpack-10.9/jetpack_vendor/automattic/jetpack-connection/src/class-manager.php
  jetpack-10.9/jetpack_vendor/automattic/jetpack-connection/src/class-package-version.php
  jetpack-10.9/jetpack_vendor/automattic/jetpack-connection/src/class-plugin-storage.php
  jetpack-10.9/jetpack_vendor/automattic/jetpack-connection/src/class-plugin.php
  jetpack-10.9/jetpack_vendor/i18n-map.php
  jetpack-10.9/readme.txt
  jetpack-10.9/vendor/composer/autoload_files.php
  jetpack-10.9/vendor/composer/autoload_static.php
  jetpack-10.9/vendor/composer/installed.json
  jetpack-10.9/vendor/composer/installed.php
  jetpack-10.9/vendor/composer/jetpack_autoload_classmap.php
  jetpack-10.9/vendor/composer/jetpack_autoload_filemap.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#3107 GH-1850: Replace create_function() with a closure
  debug-bar-cron/debug-bar-cron.php
Labels: [Type] Bug, [Status] Needs Review, PHP Compatibility

#3115 Remove Go migration Jetpack endpoint
  rest-api/vip-endpoints.php
Labels: [Status] Ready to Deploy

#2973 Search: Enable admin UI
  search/includes/classes/class-dashboard.php
  search/includes/classes/class-search.php
Labels: [Component] Search

#3108 Use PHP 8.0 for linting
  .circleci/config.yml
  vip-helpers/vip-utils.php
Labels: [Type] Maintenance, PHP Compatibility
