Repository Automattic/vip-go-mu-plugins, pull requests merged in 2022-05, with the labels that each got.

#3123 Jetpack: Update 10.9-beta2 to 10.9
  jetpack-10.9/CHANGELOG.md
  jetpack-10.9/_inc/blocks/editor-beta.asset.php
  jetpack-10.9/_inc/blocks/editor-beta.js
  jetpack-10.9/_inc/blocks/editor-experimental.asset.php
  jetpack-10.9/_inc/blocks/editor-experimental.js
  jetpack-10.9/_inc/blocks/editor-no-post-editor.asset.php
  jetpack-10.9/_inc/blocks/editor-no-post-editor.js
  jetpack-10.9/_inc/blocks/editor.asset.php
  jetpack-10.9/_inc/blocks/editor.js
  jetpack-10.9/_inc/build/admin.asset.php
  jetpack-10.9/_inc/build/admin.js
  jetpack-10.9/_inc/build/plugins-page.asset.php
  jetpack-10.9/_inc/build/plugins-page.js
  jetpack-10.9/class.jetpack.php
  jetpack-10.9/composer.json
  jetpack-10.9/jetpack.php
  jetpack-10.9/jetpack_vendor/i18n-map.php
  jetpack-10.9/readme.txt
  jetpack-10.9/vendor/autoload.php
  jetpack-10.9/vendor/autoload_packages.php
  jetpack-10.9/vendor/composer/autoload_files.php
  jetpack-10.9/vendor/composer/autoload_real.php
  jetpack-10.9/vendor/composer/autoload_static.php
  jetpack-10.9/vendor/composer/jetpack_autoload_classmap.php
  jetpack-10.9/vendor/composer/jetpack_autoload_filemap.php
  jetpack-10.9/vendor/jetpack-autoloader/class-autoloader-handler.php
  jetpack-10.9/vendor/jetpack-autoloader/class-autoloader-locator.php
  jetpack-10.9/vendor/jetpack-autoloader/class-autoloader.php
  jetpack-10.9/vendor/jetpack-autoloader/class-container.php
  jetpack-10.9/vendor/jetpack-autoloader/class-hook-manager.php
  jetpack-10.9/vendor/jetpack-autoloader/class-latest-autoloader-guard.php
  jetpack-10.9/vendor/jetpack-autoloader/class-manifest-reader.php
  jetpack-10.9/vendor/jetpack-autoloader/class-path-processor.php
  jetpack-10.9/vendor/jetpack-autoloader/class-php-autoloader.php
  jetpack-10.9/vendor/jetpack-autoloader/class-plugin-locator.php
  jetpack-10.9/vendor/jetpack-autoloader/class-plugins-handler.php
  jetpack-10.9/vendor/jetpack-autoloader/class-shutdown-handler.php
  jetpack-10.9/vendor/jetpack-autoloader/class-version-loader.php
  jetpack-10.9/vendor/jetpack-autoloader/class-version-selector.php
Labels: [Component] Jetpack

#3124 Jetpack: Default version to 10.9
  jetpack.php
Labels: [Status] Needs Review, [Component] Jetpack

#3126 Search: Fix double UI bug appearing for single sites
  search/includes/classes/class-dashboard.php
Labels: [Status] Ready to Deploy, [Component] Search

#3130 Updating Parse.ly 3.3 branch to 3.3.1
  wp-parsely-3.3/README.md
  wp-parsely-3.3/src/UI/class-metadata-renderer.php
  wp-parsely-3.3/src/UI/class-settings-page.php
  wp-parsely-3.3/src/blocks/recommendations/README.md
  wp-parsely-3.3/views/custom-metadata.php
  wp-parsely-3.3/views/json-ld.php
  wp-parsely-3.3/wp-parsely.php
Labels: [Status] Needs Review, [Component] Parse.ly

#3131 Setting Parse.ly 3.3 as the default version
  .github/workflows/parsely.yml
  tests/parsely/test-mu-parsely-integration.php
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#3039 Healthcheck that fully loads customer code and plugins before determining whether a site is healthy or not.
  000-vip-init.php
  healthcheck/class-healthcheck.php
  healthcheck/healthcheck.php
Labels: [Status] Ready to Deploy

#3135 Switch to @automattic/eslint-plugin-wpvip
  search/search-dev-tools/.babelrc.json
  search/search-dev-tools/.eslintrc.json
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
  search/search-dev-tools/src/components/app.js
  search/search-dev-tools/src/components/collapsible-list/index.js
  search/search-dev-tools/src/components/information-pane/index.js
  search/search-dev-tools/src/components/overlay/index.js
  search/search-dev-tools/src/components/query/index.js
  search/search-dev-tools/src/utils.js
Labels: [Status] Ready to Deploy, [Type] Maintenance

#3136 Search: Use dashes for query parameter in forcing index version
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy, [Component] Search

#3139 Revert "Remove Go migration Jetpack endpoint (#3115)"
  rest-api/vip-endpoints.php
Labels: [Status] Needs Review

#3150 Add Object Cache panel to Query Monitor
  qm-plugins/qm-object-cache/class-qm-collector-object-cache.php
  qm-plugins/qm-object-cache/class-qm-output-object-cache.php
  qm-plugins/qm-object-cache/css/style.css
  qm-plugins/qm-object-cache/qm-object-cache.php
  qm-plugins/qm-object-cache/readme.md
  qm-plugins/qm-object-cache/screenshot-1.png
  query-monitor.php
Labels: [Status] Ready to Deploy, [Component] Query Monitor

#3151 Revert "Remove `renovate.json`"
  .github/dependabot.yml
  renovate.json
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3155 GH-2667: fix 'Implicit conversion from float to int loses precision'
  tests/config/test-site-details-index.php
Labels: [Status] Needs Review, [Type] Maintenance, PHP Compatibility, [Status] No files to Deploy

#3158 Updating Parse.ly 3.3 branch to 3.3.2
  wp-parsely-3.3/README.md
  wp-parsely-3.3/src/UI/class-metadata-renderer.php
  wp-parsely-3.3/wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#3143 Switch to @automattic/eslint-plugin-wpvip
  __tests__/e2e/.eslintrc.js
  __tests__/e2e/bin/setup-env.sh
  __tests__/e2e/lib/data-helper.ts
  __tests__/e2e/lib/pages/media-upload-page.ts
  __tests__/e2e/lib/pages/published-page-page.ts
  __tests__/e2e/lib/pages/published-post-page.ts
  __tests__/e2e/lib/pages/search-page.ts
  __tests__/e2e/lib/pages/settings-writing-page.ts
  __tests__/e2e/lib/pages/wp-classic-editor-page.ts
  __tests__/e2e/lib/pages/wp-editor-page.ts
  __tests__/e2e/lib/playwright-helpers.ts
  __tests__/e2e/lib/wp-api-helper.ts
  package-lock.json
  package.json
Labels: [Status] Needs Review, [Type] Maintenance

#3160 Update renovate.conf
  renovate.json
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3164 Jetpack 10.9 Hotfix: Fix namespacing issue in Publicize
  jetpack-10.9/jetpack_vendor/automattic/jetpack-publicize/src/class-publicize.php
Labels: [Component] Jetpack

#3167 Add PHP 8 migration notice on non-prods
  admin-notice/admin-notice.php
Labels: [Status] Ready to Deploy

#3168 Add restrictions for wpcomvp user
  000-vip-init.php
  tests/vip-helpers/test-wpcomvip-restrictions.php
  vip-helpers/class-wpcomvip-restrictions.php
Labels: [Type] Enhancement, [Status] Ready to Deploy, [Component] Security

#3170 Skip remote_request_disabled errors from logs, they're noisy and don't actually tell us there's an issue with backend
  search/includes/classes/class-search.php
Labels: [Status] Ready to Deploy, [Component] Search

#3171 Fix flaky tests
  tests/test-performance-lastpostmodified.php
  tests/vip-helpers/test-wpcomvip-restrictions.php
Labels: [Type] Bug, [Status] Needs Review, [Component] Tests, [Status] No files to Deploy

#3172 Fix flaky tests
  tests/test-performance-lastpostmodified.php
Labels: [Type] Bug, [Status] Needs Review, [Component] Tests, [Status] No files to Deploy

#3173 Validate parameter types in the userland, not in PHP
  vip-helpers/class-wpcomvip-restrictions.php
Labels: [Type] Bug, [Status] Needs Review

#3176 Check if headers has already been sent before sending new ones
  security.php
  wpcom-vip-two-factor/is-jetpack-sso.php
Labels: [Type] Bug, [Status] Needs Review

#3177 Fix PHP warnings
  security/machine-user.php
  security/password.php
Labels: [Type] Bug, [Status] Ready to Deploy

#3178 Skip problematic plugins on WP installation
  jetpack.php
  query-monitor.php
  two-factor.php
  vaultpress.php
  vip-support.php
Labels: [Type] Bug, [Status] Ready to Deploy

#3180 Update debug-bar to 1.1.3
  debug-bar.php
  debug-bar/debug-bar.php
  debug-bar/panels/class-debug-bar-wp-http.php
  debug-bar/panels/class-debug-bar-wp-query.php
  debug-bar/readme.txt
Labels: [Status] Ready to Deploy

#3175 SDI: Index additional plugin update data
  config/class-site-details-index.php
  tests/config/test-site-details-index.php
Labels: [Status] Ready to Deploy

#3183 Updating Akismet to 4.2.4
  akismet.php
  akismet/akismet.php
  akismet/class.akismet-admin.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/config.php
  akismet/views/connect-jp.php
  akismet/views/get.php
  akismet/views/stats.php
Labels: [Status] Ready to Deploy, [Component] Akismet

#3187 Update PHP dev dependencies
  composer.json
  composer.lock
Labels: [Status] Needs Review, dependencies, [Type] Maintenance, [Status] No files to Deploy

#3188 Update actions/dependency-review-action to 1.0.2
  .github/workflows/dependency-review.yml
Labels: [Status] Needs Review, dependencies

#3186 Update WPComVIP_Restrictions
  tests/vip-helpers/test-wpcomvip-restrictions.php
  vip-helpers/class-wpcomvip-restrictions.php
Labels: [Type] Enhancement, [Status] Needs Review, [Component] Security

#3189 Update npm dependencies and lock file maintenance
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
Labels: [Status] Needs Review, dependencies, [Type] Maintenance

#3190 Fix regression that was introduced by varying the by adding unique headers, use body of the query to calculate the hash
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-search.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Ready to Deploy

#3193 Add CI job for WP 5.9.4
  .circleci/config.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3194 Fix "Undefined index" in `wpcom_vip_lost_password_limit()`
  security.php
  tests/test-security.php
Labels: [Type] Bug, [Status] Ready to Deploy, [Pri] High, [Component] Security

#3192 GH-3179: more robust notice dismissal
  admin-notice/class-admin-notice-controller.php
  admin-notice/js/script.js
Labels: [Type] Bug, [Status] Ready to Deploy

#3195 Ensure we are using the latest WP branch release
  .circleci/config.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#3196 Fix CI
  .circleci/config.yml
Labels: [Type] Bug, [Status] Needs Review, [Pri] Blocker, [Status] No files to Deploy

#3197 Search: Fix bug where health validate-counts on multisite returns incorrect results
  search/includes/classes/commands/class-healthcommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#3200 Rename "Automattic File Hosting Service" to "VIP File Service"
  a8c-files.php
Labels: [Status] Ready to Deploy
