Repository Automattic/vip-go-mu-plugins, pull requests merged in 2022-11, with the labels that each got.

#3832 Query Monitor: Add cron panel
  qm-plugins/qm-cron/class-qm-cron-collector.php
  qm-plugins/qm-cron/class-qm-cron-output-html.php
  qm-plugins/qm-cron/qm-cron.php
  query-monitor.php
Labels: [Status] Ready to Deploy, [Component] Query Monitor

#3841 e2e: addImage() needs to click instead of tab
  __tests__/e2e/lib/pages/wp-editor-page.ts
Labels: [Component] Tests, [Status] No files to Deploy

#3842 ci: Fix core tests
  000-vip-init.php
  files/init-filesystem.php
  vip-helpers/vip-notoptions-mitigation.php
Labels: [Type] Bug, [Status] Ready to Deploy, [Component] Tests

#3846 Add vip_get_hyper_servers()
  001-core/constants.php
  tests/001-core/test-constants.php
  vip-helpers/vip-utils.php
Labels: [Status] Ready to Deploy

#3847 Add setup instructions on dependencies
  README.md
Labels: [Status] No files to Deploy

#3848 feat(prometheus): Add `is_opcache_available()`
  prometheus-collectors/class-opcache-collector.php
Labels: [Type] Enhancement, [Status] Ready to Deploy

#3849 fix(vip-helpers): Work around another Yoast bug
  vip-helpers/vip-debug-bar-panels.php
  vip-helpers/vip-utils.php
Labels: [Type] Bug, [Status] Ready to Deploy

#3852 CI Observability: Integrate ForeSight to tests phases of CI
  .github/workflows/e2e.yml
  .github/workflows/search-e2e.yml
  .lintstagedrc
  __tests__/e2e/playwright.config.ts
Labels: [Status] Needs Review, [Status] No files to Deploy

#3853 fix(files): `touch()` should fail if `fclose()` fails
  files/class-vip-filesystem-stream-wrapper.php
  tests/files/test-vip-filesystem-stream-wrapper.php
Labels: [Type] Bug, [Status] Ready to Deploy

#3865 fix(files): Clear stats cache when upload of an empty file fails
  files/class-vip-filesystem-stream-wrapper.php
Labels: [Type] Bug, [Status] Ready to Deploy

#3845 Fix wp-parsely integration tests
  bin/test.sh
  tests/bootstrap.php
  tests/parsely/test-mu-parsely-integration.php
Labels: [Status] Needs Review, [Component] Parse.ly, [Component] Tests

#3868 Update Cypress reporters for ForeSight Integration
  .github/workflows/search-e2e.yml
  package-lock.json
  package.json
  tests/search/e2e/config.json
  tests/search/e2e/cypress-reporter-config.json
  tests/search/e2e/cypress.config.js
Labels: [Type] Maintenance

#3873 ci: Fix coverage generation
  .github/workflows/ci.yml
Labels: [Type] Bug, [Component] Tests, [Status] No files to Deploy

#3882 Check earlier if display-name is set
  vip-support/class-vip-support-cli.php
Labels: [Status] Ready to Deploy

#3872 ci: Update E2E workflow
  .github/workflows/e2e.yml
  __tests__/e2e/playwright.config.ts
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Tests

#3874 chore(deps): Bump ramsey/composer-install to 2.2.0
  .github/actions/run-wp-tests/action.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Tests

#3888 ci: Fix Jetpack bootstrapping issue
  .github/actions/prepare-source/action.yml
  .github/workflows/ci.yml
  .github/workflows/coverage-develop.yml
  .github/workflows/e2e.yml
  .github/workflows/parsely.yml
  .github/workflows/search-e2e.yml
Labels: [Type] Bug, [Component] Tests, [Status] No files to Deploy

#3887 Make helper methods in WPCOM_VIP_CLI_Command public and static
  vip-helpers/vip-wp-cli.php
Labels: [Status] Ready to Deploy

#3889 ci: Fix a typo in tag-release.yml
  .github/workflows/tag-release.yml
Labels: [Status] Needs Review

#3890 ci: Update deploy workflow
  .github/workflows/deploy.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#3892 ci: Fix rsync command in deploy.yml
  .github/workflows/deploy.yml
Labels: [Type] Bug, [Status] No files to Deploy

#3899 Search: Auto re-build post index when mapping is bad
  search/includes/classes/class-health.php
  search/includes/classes/class-settingshealthjob.php
  tests/search/includes/classes/test-class-health.php
Labels: [Status] Ready to Deploy, [Component] Search

#3910 CI: Add WP 6.0 to matrix for single sites
  .github/workflows/ci.yml
Labels: [Status] No files to Deploy

#3918 Prometheus: update the endpoint and query_var to be more unique, remove proxy restriction
  prometheus/inc/class-plugin.php
Labels: [Status] Ready to Deploy

#3909 Search: Roll out auto rebuilding bad index feature to 25%
  lib/feature/class-feature.php
  search/includes/classes/class-settingshealthjob.php
Labels: [Status] Ready to Deploy, [Component] Search

#3919 Prometheus: switch rendering logic to only care about specific path, rather than a registered query var
  prometheus/inc/class-plugin.php
Labels: [Status] Ready to Deploy

#3923 fix: Fix code style
  lib/environment/class-environment.php
  lib/helpers/environment.php
Labels: [Type] Maintenance, [Status] No files to Deploy

#3925 test: Remove checks against the PHP version from the code
  .github/actions/run-wp-tests/action.yml
  bin/pretest.sh
  composer.lock
  tests/bootstrap.php
  z-client-mu-plugins.php
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Tests

#3933 PR Template: Add roll out to checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review, [Status] No files to Deploy
