Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-01, with the labels that each got.

#4004 GH-3754: Fix wpcom_vip_disable_new_relic_js being called incorrectly
  misc.php
Labels: [Type] Bug, [Status] Ready to Deploy

#4011 CI: Allow tests to run for outside contributors
  .github/workflows/ci.yml
  .github/workflows/core-tests.yml
  .github/workflows/lint.yml
  .github/workflows/search-dev-tools.yml
Labels: [Status] No files to Deploy

#4016 Wrap function_exists() for is_local_env()
  000-debug/debug-mode.php
Labels: [Status] Ready to Deploy

#4017 Temporarily re-add and re-include the Statsd lib
  000-vip-init.php
  lib/statsd/class-statsd.php
Labels: [Status] Needs Review

#4021 CI: Only run search-e2e workflow when search path is modified and on PRs only
  .github/workflows/search-e2e.yml
Labels: [Status] No files to Deploy

#4023 chore(deps): Lock file maintenance
  __tests__/e2e/package-lock.json
  package-lock.json
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
Labels: [Status] Needs Review, dependencies, [Type] Maintenance

#4024 ci: Set DO_NOT_TRACK=1 for E2E tests
  .github/workflows/e2e.yml
Labels: [Status] Ready to Deploy, [Type] Maintenance, [Component] Tests

#4022 chore(deps): Update PHP require-dev transitive dependencies
  composer.lock
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4029 Composer: Remove Composer PHPCS plugin depedency
  composer.json
Labels: [Pri] Low, dependencies, [Type] Maintenance, [Status] No files to Deploy

#4025 ci: Update E2E workflow
  .github/workflows/e2e.yml
  __tests__/e2e/bin/setup-env.sh
Labels: [Type] Maintenance, [Component] Tests

#4001 VIP Request Block: Add function to allow for blocking by partial User Agent string.
  lib/class-vip-request-block.php
  tests/lib/test-vip-request-block.php
Labels: [Status] Ready to Deploy

#4035 Query Monitor: Add tab for DB Connections
  qm-plugins/qm-db-connections/class-qm-db-connections-collector.php
  qm-plugins/qm-db-connections/class-qm-db-connections-output-html.php
  qm-plugins/qm-db-connections/qm-db-connections.php
  query-monitor.php
Labels: [Component] Query Monitor

#4036 Search: Add version of EP to footer text
  search/includes/classes/class-dashboard.php
Labels: [Status] Ready to Deploy, [Component] Search

#4037 Set wp-parsely 3.6 as the default version
  wp-parsely.php
Labels: [Component] Parse.ly

#4039 Unregister JP-related cron events when disabled
  cron/cron.php
Labels: [Status] Needs Review

#4043 Implement more logging around indexing and health jobs
  search/includes/classes/class-health.php
  search/includes/classes/class-healthjob.php
  search/includes/classes/class-queue.php
  search/includes/classes/class-settingshealthjob.php
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#4045 Jetpack: Make default 11.7
  jetpack.php
Labels: [Component] Jetpack

#4046 Query Monitor (VIP): Fix link for commit
  qm-plugins/qm-vip/class-qm-vip-output-html.php
Labels: [Component] Query Monitor

#4047 [BB8-9998] Search Dev Tools: Display current algorithm version
  search/search-dev-tools/search-dev-tools.php
Labels: [Component] Search

#4048 Debug Bar: Only trigger deprecation once every 10 minutes and on admin
  debug-bar.php
Labels: [Status] Ready to Deploy

#4050 Search: Change frequency of cron jobs that run maybe_alert_for_field_count and maybe_alert_for_average_queue_time
  search/includes/classes/class-fieldcountgaugejob.php
  search/includes/classes/class-healthjob.php
  search/includes/classes/class-queuewaittimejob.php
Labels: [Status] Ready to Deploy, [Component] Search

#4051 CI: Only run Search Dev Tools build on certain directory
  .github/workflows/search-dev-tools.yml
Labels: [Status] No files to Deploy

#4056 Search: Do maybe_self_heal() onto an hourly cron
  search/includes/classes/class-versioning.php
Labels: [Component] Search

#4058 ci: Update E2E workflow
  .github/workflows/e2e.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#4080 Remove scripts for updating Jetpack subtree
  bin/add-jetpack-subtree.sh
  bin/update-jetpack-subtree.sh
Labels: [Status] Needs Review, [Status] No files to Deploy

#4076 CI: [e2e workflow] update dev-env parameters to use trunk wordpress and explicitly disable mailhog
  __tests__/e2e/bin/setup-env.sh
Labels: [Status] No files to Deploy

#4044 Disable Contact Form 7 upload cleanup if it ignores WPCF7_UPLOADS_TMP…
  plugin-fixes.php
Labels: [Status] Ready to Deploy

#3989 Prom: speed things up by moving out the rendering logic into a non-WP endpoint
  lib/utils/class-context.php
  prometheus-collectors/class-post-stats-collector.php
  prometheus/endpoint.php
  prometheus/inc/class-plugin.php
Labels: [Status] Ready to Deploy
