Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-06, with the labels that each got.

#4438 CI: Add link at end of post to tag release for production
  .github/workflows/changelog-summary.yml
  .github/workflows/tag-release.yml
  ci/changelog-summary.php
Labels: [Status] Needs Review, [Status] No files to Deploy

#4540 Revert "chore(deps-dev): Bump wp-cli/wp-cli from 2.7.1 to 2.8.0"
  composer.json
  composer.lock
Labels: [Status] Needs Review

#4546 Query Monitor: Only enable on non-prods if admin bar is enabled
  query-monitor.php
Labels: [Component] Query Monitor

#4559 chore(deps): Update search-dev-tools dependencies
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4560 chore(dev-deps): Update dependencies for E2E tests
  __tests__/e2e/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4561 fix: Type error when callable is not a method
  search/includes/classes/class-search.php
Labels: [Type] Bug, [Component] Search

#4570 test: Fix flaky tests
  tests/config/test-site-details-index.php
  tests/config/test-sync.php
Labels: [Type] Bug, [Component] Tests

#4574 chore(dev-deps): Update Playwright
  __tests__/e2e/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4575 chore(dev-deps): Update Search DevTools dependencies
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4577 ci: Add WP 6.1 to the Matrix
  .github/workflows/ci.yml
  tests/001-core/test-privacy.php
Labels: [Type] Maintenance, [Status] No files to Deploy

#4576 ci: Update internal actions
  .github/actions/run-wp-tests/action.yml
Labels: [Status] Needs Review, [Type] Maintenance, [Status] No files to Deploy

#4578 ci: Update Parse.ly CI workflows to use PHP 8.0
  .github/workflows/parsely.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#4584 ci: Fix duplicate workflow name
  .github/workflows/search-dev-tools.yml
Labels: [Type] Bug, [Status] Retro Review, github_actions

#4594 Query Monitor: Do not enable by default for non-prods
  query-monitor.php
Labels: [Component] Query Monitor

#4605 CI: Add objects.githubusercontent.com to safelist of step-security
  .github/workflows/e2e.yml
Labels: [Status] No files to Deploy

#4551 Search: Fix bug where validate-contents isn't fixing when --inspect
  search/includes/classes/class-health.php
  search/includes/classes/commands/class-healthcommand.php
  tests/search/includes/classes/test-class-health.php
Labels: [Component] Search

#4617 Add auth tokens through VIP_SERVICES_AUTH_TOKENS instead, if available
  config/class-site-details-index.php
Labels: [Status] Needs Review

#4618 fix: Make installatoin in dev env complete without warnings
  000-vip-init.php
  001-cron.php
  cron/cron.php
  prometheus/inc/class-plugin.php
Labels: [Type] Bug

#4606 Search: Remove exception list
  search/includes/classes/class-search.php
Labels: [Component] Search

#4625 CI: Remove added `v` for `shivammathur/setup-php`
  .github/workflows/changelog-summary-prod.yml
Labels: [Status] No files to Deploy

#4627 CI: Add write permissions to pull-requests to fix labels adding
  .github/workflows/changelog-summary-prod.yml
Labels: [Status] No files to Deploy

#4458 Add VIP Integrations framework
  .dockerignore
  integrations/block-data-api.php
  integrations/integration.php
  integrations/integrations.php
  phpcs.xml.dist
  tests/vip-integrations/fake-integration.php
  tests/vip-integrations/test-vip-integrations.php
  vip-integrations.php
  vip-integrations/.gitkeep
Labels: [Status] Needs Review

#4610 VaultPress: Prevent overriding VIP_VAULTPRESS_SKIP_LOAD constant
  cron/cron.php
  vaultpress.php
  vip-jetpack/connection-pilot/class-jetpack-connection-cli.php
  vip-jetpack/connection-pilot/class-jetpack-connection-pilot.php
Labels: [Status] Needs Review

#4651 Disable settings health job on non-prods
  search/includes/classes/class-settingshealthjob.php
Labels: [Status] Needs Review, [Component] Search
