Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-04, with the labels that each got.

#4305 chore(deps): Update @babel/core, webpack, and css-minimizer-webpack-plugin
  search/search-dev-tools/build/bundle.css
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
Labels: dependencies, [Type] Maintenance, [Component] Tests

#4304 chore(dev-deps): Update eslint-plugin-cypress, @wordpress/api-fetch, @wordpress/env
  package-lock.json
Labels: dependencies, [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4306 Fix fatal error in "widget updated" event
  vip-parsely/Telemetry/Events/track-widget-updated.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#4298 prevent usort'ing NULL
  qm-plugins/qm-alloptions/class-qm-collector-alloptions.php
Labels: [Component] Query Monitor

#4327 Search: Skip query integration if no active indexes present
  search/includes/classes/class-search.php
Labels: [Component] Search

#4330 Revert "fix: Do not load client MU plugins when WP is being installed"
  vip-helpers/vip-utils.php
Labels: [Status] Reverted

#4326 Vaultpress: Remove from mandatory JP modules
  vip-jetpack/jetpack-mandatory.php
Labels: [Component] VaultPress

#4343 Revert "Disables Parse.ly if VIP_PARSELY_SKIP_LOAD or VIP_IS_FEDRAMP constant is set"
  000-vip-init.php
  tests/parsely/test-mu-parsely-integration.php
  wp-parsely.php
Labels: [Status] Needs Review

#4342 Add VIP_PARSELY_ENABLED constant to enable / disable wp-parsely plugin
  000-vip-init.php
  tests/parsely/test-mu-parsely-integration.php
  wp-parsely.php
Labels: [Status] Ready to Deploy

#4345 Alerts: Add PagerDuty
  lib/utils/class-alerts.php
  tests/lib/utils/class-testable-alerts.php
  tests/lib/utils/test-alerts.php
Labels: [Status] Needs Review

#4347 ci: Remove Foresight
  .github/workflows/e2e.yml
  .github/workflows/search-e2e.yml
  __tests__/e2e/playwright.config.ts
  package-lock.json
  package.json
Labels: [Type] Maintenance, [Status] No files to Deploy

#4348 Search: Rollout to 55% of production
  lib/feature/class-feature.php
Labels: [Component] Search

#4356 chore(dev-deps): Update dependencies for E2E tests
  __tests__/e2e/package-lock.json
  __tests__/e2e/package.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4357 chore(dev-deps): Update dependencies for SDT
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4358 chore(dev-deps): Update dependencies for ES E2E tests
  package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4355 Search: Fix syntax error in confirming update active index version when --using-versions
  search/includes/classes/commands/class-corecommand.php
Labels: [Status] Ready to Deploy, [Component] Search

#4374 Search: Rollout to 70%
  lib/feature/class-feature.php
Labels: [Status] Needs Review, [Component] Search

#4380 CI: Do not add Reverted PRs to changelog summary
  ci/changelog-summary.php
Labels: [Status] No files to Deploy

#4312 Don't add objects to queue if index doesn't exist
  search/includes/classes/class-queue.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Component] Search

#4394 Search: Roll out to 85%
  lib/feature/class-feature.php
Labels: [Component] Search

#4393 Tests: PHPUnit 10 Compatibility Fixes
  tests/cache/test-vary-cache.php
  tests/files/acl/test-acl.php
  tests/files/acl/test-pre-wp-utils.php
  tests/files/test-wp-filesystem-vip.php
  tests/lib/environment/test-class-environment.php
  tests/lib/helpers/test-environment.php
  tests/prometheus/test-prometheus.php
  tests/search/includes/classes/test-class-queue.php
  tests/search/includes/classes/test-class-search.php
  tests/test-vip-cache-manager.php
Labels: [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4361 WP-CLI: Unblock `wp db tables` command
  lib/helpers/wp-cli-db/class-wp-cli-db.php
Labels: [Status] Needs Docs, Do not merge!

#4396 QM Cron: Add safeguarding for dev-env where data is not fully available
  qm-plugins/qm-cron/class-qm-cron-output-html.php
Labels: [Component] Query Monitor

#4372 Query Monitor: Add more information to VIP panel and structure better
  qm-plugins/qm-vip/class-qm-vip-collector.php
  qm-plugins/qm-vip/class-qm-vip-output-html.php
  qm-plugins/qm-vip/qm-vip.php
Labels: [Component] Query Monitor

#4405 Update qm-plugins to be compat with new query-monitor version
  qm-plugins/qm-alloptions/class-qm-collector-alloptions.php
  qm-plugins/qm-alloptions/class-qm-data-alloptions.php
  qm-plugins/qm-alloptions/class-qm-output-html-alloptions.php
  qm-plugins/qm-alloptions/qm-alloptions.php
  qm-plugins/qm-apcu-cache/class-qm-collector-apcu-cache.php
  qm-plugins/qm-apcu-cache/class-qm-output-html-apcu-cache.php
  qm-plugins/qm-apcu-cache/qm-apcu-cache.php
  qm-plugins/qm-cron/class-qm-collector-cron.php
  qm-plugins/qm-cron/class-qm-data-cron.php
  qm-plugins/qm-cron/class-qm-output-html-cron.php
  qm-plugins/qm-cron/qm-cron.php
  qm-plugins/qm-db-connections/class-qm-collector-db-connections.php
  qm-plugins/qm-db-connections/class-qm-data-db-connections.php
  qm-plugins/qm-db-connections/class-qm-output-html-db-connections.php
  qm-plugins/qm-db-connections/qm-db-connections.php
  qm-plugins/qm-object-cache/class-qm-data-object-cache.php
  qm-plugins/qm-object-cache/collectors/class-qm-collector-object-cache-ops.php
  qm-plugins/qm-object-cache/collectors/class-qm-collector-object-cache-slow-ops.php
  qm-plugins/qm-object-cache/collectors/class-qm-collector-object-cache.php
  qm-plugins/qm-object-cache/html/class-qm-output-html-object-cache-ops.php
  qm-plugins/qm-object-cache/html/class-qm-output-html-object-cache-slow-ops.php
  qm-plugins/qm-object-cache/html/class-qm-output-html-object-cache.php
  qm-plugins/qm-object-cache/qm-object-cache.php
  qm-plugins/qm-vip/class-qm-collector-vip.php
  qm-plugins/qm-vip/class-qm-data-vip.php
  qm-plugins/qm-vip/class-qm-output-html-vip.php
  qm-plugins/qm-vip/qm-vip.php
Labels: [Type] Maintenance, [Component] Query Monitor

#4379 Search: Add ability to deactivate versions
  search/includes/classes/class-versioning.php
  search/includes/classes/commands/class-versioncommand.php
  tests/search/includes/classes/test-class-versioning.php
Labels: [Component] Search
