Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-10, with the labels that each got.

#4911 Search: Increase character search length to 510 characters
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-search.php
Labels: [Component] Search

#4928 fix(qm-object-cache): fix closing markup for tabs nesting
  qm-plugins/qm-object-cache/html/class-qm-output-html-object-cache-group-stats.php
Labels: [Component] Query Monitor

#4948 chore: update search-dev-tools dependencies
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
  search/search-dev-tools/package.json
Labels: [Status] Retro Review, dependencies

#4949 chore(dev-deps): update dependencies for E2E tests
  __tests__/e2e/package-lock.json
  __tests__/e2e/package.json
Labels: [Status] Retro Review, dependencies, [Type] Maintenance

#4944 test: fix "test method is not public" warning
  tests/integrations/test-integration-vip-config.php
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Tests

#4962 Remove deprecated filter `http_api_transports`
  files/class-curl-streamer.php
  tests/files/test-curl-streamer.php
Labels: [Status] Needs Review

#4969 CANTINA-955: Deprecate `SEARCH_DEV_TOOLS_CAP` and use `vip_search_dev_tools_cap` filter instead. Also decouples query monitor
  search/includes/classes/class-search.php
  search/search-dev-tools/search-dev-tools.php
  tests/search/includes/classes/test-class-search.php
Labels: [Status] Needs Review, [Component] Search

#4975 CANTINA-953: Add `vip_block_wp_mail` filter
  tests/mock-constants.php
  tests/test-vip-mail.php
  vip-mail.php
Labels: [Status] Needs Review, [Status] Needs Docs

#4970 fix(files): better handle directories in `move()`
  files/class-wp-filesystem-vip.php
Labels: [Type] Bug

#4985 Remove `WPCOM_VIP_QUERY_LOG`
  misc.php
Labels: [Status] Needs Review
