Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-02, with the labels that each got.

#4107 Fix failing test test__skip_vip_link_if_customer_link_set
  tests/001-core/test-privacy.php
Labels: [Status] No files to Deploy

#4108 Jetpack: Make default 11.8
  jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#4110 Skip loading Jetpack for FedRAMP sites by default
  000-vip-init.php
  lib/utils/class-context.php
Labels: [Status] Needs Review, [Component] Jetpack

#4115 chore(deps): Fix security issues in transitive dependencies
  package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4114 chore: Update phpcs.xml.dist to reflect recent changes
  phpcs.xml.dist
Labels: [Type] Maintenance, [Status] No files to Deploy

#4118 VIP_Request_Block: Do not log blocks in New Relic
  lib/class-vip-request-block.php
Labels: [Status] Ready to Deploy

#4111 Revert "Reverting wp-cli-db"
  000-pre-vip-config/requires.php
  lib/helpers/wp-cli-db/class-config.php
  lib/helpers/wp-cli-db/class-wp-cli-db.php
Labels: [Status] Ready to Deploy

#4082 Query Monitor: Revise Object Cache to play with get_stats()
  qm-plugins/qm-object-cache/class-qm-collector-object-cache.php
  qm-plugins/qm-object-cache/class-qm-output-object-cache.php
  qm-plugins/qm-object-cache/collectors/class-qm-collector-object-cache-ops.php
  qm-plugins/qm-object-cache/collectors/class-qm-collector-object-cache-slow-ops.php
  qm-plugins/qm-object-cache/collectors/class-qm-collector-object-cache.php
  qm-plugins/qm-object-cache/css/style.css
  qm-plugins/qm-object-cache/html/class-qm-output-object-cache-ops.php
  qm-plugins/qm-object-cache/html/class-qm-output-object-cache-slow-ops.php
  qm-plugins/qm-object-cache/html/class-qm-output-object-cache.php
  qm-plugins/qm-object-cache/qm-object-cache.php
  qm-plugins/qm-object-cache/screenshot-1.png
Labels: [Status] Ready to Deploy, [Component] Query Monitor

#4126 Environment: account for batch pods
  lib/environment/class-environment.php
  tests/lib/environment/test-class-environment.php
Labels: [Status] Ready to Deploy

#4135 Update the email address in overdue notice
  security/class-lockout.php
Labels: [Status] Ready to Deploy

#4128 Add more files to ignore list
  .dockerignore
Labels: Do not merge!

#4151 Search Dev Tools: add class name to CollapsibleList Component
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/src/components/collapsible-list/index.js
Labels: [Status] Ready to Deploy, [Component] Search

#4152 Search Dev Tools: Add title and vip-collapse-ol to classes in ol element in CollapsibleList
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/src/components/collapsible-list/index.js
Labels: [Status] Ready to Deploy, [Component] Search

#4153 Disable Codecov annotations
  .github/codecov.yml
Labels: [Status] No files to Deploy

#4145 Search: Add should_load_new_ep() for upcoming rollout of next ElasticPress version
  .wp-env.json
  admin-notice/admin-notice.php
  lib/feature/class-feature.php
  search/includes/classes/class-health.php
  search/includes/classes/class-search.php
  search/includes/functions/ep-get-query-log.php
  tests/search/e2e/integration/features/custom-results.spec.js
  tests/search/e2e/integration/features/facets.spec.js
  tests/search/e2e/integration/features/protected-content.spec.js
  tests/search/e2e/integration/features/related-posts.spec.js
  tests/search/e2e/integration/features/search/search.spec.js
  tests/search/e2e/integration/features/search/synonyms.spec.js
  tests/search/e2e/integration/features/search/weighting.spec.js
  tests/search/e2e/integration/features/terms.spec.js
  tests/search/e2e/integration/features/woocommerce.spec.js
  tests/search/e2e/integration/general.spec.js
  tests/search/e2e/integration/indexables/user.spec.js
  tests/search/e2e/integration/wp-cli.spec.js
  tests/search/e2e/support/commands.js
  tests/search/e2e/support/global-hooks.js
  tests/search/e2e/support/index.js
  tests/search/e2e/wordpress-files/test-plugins/vip-woocommerce-meta-allow-list.php
Labels: [Component] Search

#4134 Add vip_send_wplogin_header()
  security.php
Labels: [Status] Ready to Deploy

#4162 Add get_stats() to object cache drop-ins
  drop-ins/object-cache/object-cache-next.php
  drop-ins/object-cache/object-cache-stable.php
Labels: [Status] Ready to Deploy

#4129 Jetpack: Removed unneeded versions
  jetpack.php
  tests/test-jetpack.php
Labels: [Status] Ready to Deploy, [Component] Jetpack

#4164 Add and set wp-parsely 3.7 as the default version
  wp-parsely.php
Labels: [Status] Ready to Deploy, [Component] Parse.ly

#4127 Take #3: WP_CLI_DB - Allow certain `wp db` subcommands
  000-pre-vip-config/requires.php
  lib/helpers/wp-cli-db/class-config.php
  lib/helpers/wp-cli-db/class-vip-db-command.php
  lib/helpers/wp-cli-db/class-wp-cli-db.php
  tests/lib/helpers/test-wp-cli-db.php
Labels: [Status] Ready to Deploy

#4168 Check for method existence of should_load_new_ep()
  admin-notice/admin-notice.php
  search/includes/classes/class-health.php
  search/includes/functions/ep-get-query-log.php
Labels: [Status] Needs Review

#4169 Search: Roll out ElasticPress-next to 10% of production environments
  lib/feature/class-feature.php
Labels: [Status] Ready to Deploy, [Component] Search
