Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-05, with the labels that each got.

#4416 Update Akismet to 5.1
  akismet.php
  akismet/_inc/akismet-frontend.js
  akismet/akismet.php
  akismet/changelog.txt
  akismet/class.akismet-admin.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/config.php
  akismet/views/notice.php
  akismet/views/stats.php
Labels: [Component] Akismet

#4421 chore(dev-deps): Update Playwright to 1.33.0
  __tests__/e2e/package-lock.json
Labels: dependencies, [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4422 chore(dev-deps): Update Search Dev Tools
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4423 chore(dev-deps): Update dependencies for ES E2E tests
  package-lock.json
  package.json
Labels: [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4417 vip_strict_sanitize_username(): return empty string if not string
  security.php
Labels: [Status] Ready to Deploy

#4426 Jetpack: Make 12.1 default
  jetpack.php
  tests/test-jetpack.php
Labels: [Component] Jetpack

#4430 Search: Rollout new Search to 100%
  admin-notice/admin-notice.php
  lib/feature/class-feature.php
  search/includes/classes/class-search.php
  tests/search/includes/classes/test-class-health.php
  tests/search/includes/classes/test-class-search.php
  tests/search/includes/classes/test-concurrency-limiter.php
  tests/search/test-search-dev-tools.php
Labels: [Component] Search

#4439 Search: Fix fatal `Warning: Undefined property: Automattic\VIP\Search\Queue::$alerts`
  search/includes/classes/class-queue.php
Labels: [Component] Search

#4447 Add support for SDS that sits in the customer namespace
  config/class-site-details-index.php
Labels: [Status] Needs Review

#4462 Revert "chore(deps-dev): bump @wordpress/env from 6.0.0 to 7.0.0"
  package-lock.json
  package.json
Labels: [Status] No files to Deploy

#4461 tests: Use `assertEqualsWithDelta()` to check activation time
  tests/search/includes/classes/test-class-versioning.php
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4465 tests: Do not contact external sites in Site_Details_Index_Test
  tests/config/test-site-details-index.php
Labels: [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4482 chore(dev-deps): Update search-dev-tools dependencies
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy

#4508 ci: Workaround for failing core tests
  .github/workflows/core-tests.yml
Labels: [Type] Maintenance, [Status] No files to Deploy

#4509 chore(deps): Update search-dev-tools dependencies
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, javascript

#4510 chore(dev-deps): Update dependencies for E2E tests
  __tests__/e2e/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy, javascript

#4511 chore(dev-deps): Update dependencies for ES E2E tests
  package-lock.json
  package.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy, javascript

#4464 tests: Fix `expectException()` usage
  tests/cache/test-vary-cache.php
  tests/files/acl/test-acl.php
  tests/files/acl/test-pre-wp-utils.php
  tests/files/test-wp-filesystem-vip.php
  tests/test-vip-cache-manager.php
Labels: [Type] Maintenance, [Component] Tests, [Status] No files to Deploy

#4519 chore(dev-deps): Update search-dev-tools dependencies
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy, javascript

#4531 Search: Add lock for `sweep_jobs()`
  search/includes/classes/queue/class-cron.php
Labels: [Component] Search
