Repository Automattic/vip-go-mu-plugins, pull requests merged in 2023-11, with the labels that each got.

#4984 Private sites: Disable Jetpack AI
  security/class-private-sites.php
Labels: [Component] Jetpack

#5001 CI: Update WP Matrix to reflect current status
  .github/workflows/ci.yml
Labels: [Status] No files to Deploy

#5018 Add and set wp-parsely 3.11 as the default version
  wp-parsely.php
Labels: [Status] Needs Review, [Component] Parse.ly

#5021 fix(files): account for instantiation of `WP_Filesystem_VIP` without arguments
  files/class-wp-filesystem-vip.php
Labels: [Type] Bug, [Status] Needs Review

#5041 Search e2e: Fix tests with recent updates
  tests/search/e2e/integration/features/woocommerce.spec.js
  tests/search/e2e/integration/indexables/user.spec.js
Labels: [Status] No files to Deploy

#5052 CI: Remove PHP 7.4 and 8.0 from matrix
  .github/workflows/ci.yml
Labels: [Status] No files to Deploy

#5040 Query monitor tweaks: Implement a new Header outputter for PHP Errors.
  qm-plugins/qm-limited-header-php-errors/output/headers/php-errors.php
  query-monitor.php
Labels: [Component] Query Monitor

#5058 CANTINA-1000: Prevent impact of filtered formatted ES args when `wp vip-search health validate-counts` runs
  search/includes/classes/class-health.php
Labels: [Status] Needs Review, [Component] Search
