Repository Automattic/vip-go-mu-plugins, pull requests merged in 2024-11, with the labels that each got.

#5975 Explicitly supply accept: image/webp for requests to webp images
  files/class-api-client.php
Labels: [Status] Needs Review

#5965 WP Parse.ly: Fix issue with support user bypass
  vip-parsely/vip-parsely.php
Labels: [Component] Parse.ly

#5989 ci: use preconfigured WP image if available
  .github/workflows/e2e.yml
  __tests__/e2e/bin/setup-env.sh
Labels: [Type] Maintenance
