Repository Automattic/vip-go-mu-plugins, pull requests merged in 2024-03, with the labels that each got.

#5301 build(deps): update GitHub actions
  .github/actions/run-wp-tests/action.yml
  .github/workflows/changelog-summary-prod.yml
  .github/workflows/changelog-summary-staging.yml
  .github/workflows/core-tests.yml
  .github/workflows/lint.yml
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy, github_actions

#5302 chore(dev-deps): update dependencies for E2E tests
  __tests__/e2e/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy, javascript

#5303 chore(deps): update search-dev-tools dependencies
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, javascript

#5274 Disable auto-resend with fallback email
  tests/test-vip-mail.php
  vip-mail.php
Labels: [Status] Needs Review

#5272 Use a relative WPMU_PLUGIN_DIR config for VIP mu-plugins
  000-vip-init.php
  001-core/privacy.php
  cache/README.md
  cache/examples/segmentation-beta/beta.php
  integrations/block-data-api.php
  integrations/vip-governance.php
  jetpack.php
  lib/sunrise/sunrise.php
  qm-plugins/qm-vip/class-qm-collector-vip.php
  query-monitor.php
  two-factor.php
  vip-helpers/vip-deprecated.php
  vip-helpers/vip-utils.php
  vip-jetpack/jetpack-mandatory.php
  wpcom-vip-two-factor/sms-provider.php
Labels: [Status] Ready to Deploy

#5322 Add and set wp-parsely 3.14 as the default version
  wp-parsely.php
Labels: [Status] Needs Review, [Component] Parse.ly

#5321 Update Akismet to 5.3.1
  akismet/.htaccess
  akismet/_inc/akismet-admin.css
  akismet/_inc/akismet-frontend.js
  akismet/_inc/img/icon-external.svg
  akismet/_inc/rtl/akismet-admin-rtl.css
  akismet/akismet.php
  akismet/class.akismet-admin.php
  akismet/class.akismet-cli.php
  akismet/class.akismet-rest-api.php
  akismet/class.akismet.php
  akismet/readme.txt
  akismet/views/config.php
  akismet/views/notice.php
Labels: [Status] Needs Review, [Type] Maintenance, [Component] Akismet

#5265 Filter the font directory to work with the VIP Filesystem
  files/class-vip-filesystem.php
  tests/files/test-vip-filesystem.php
Labels: [Status] Ready to Deploy

#5331 chore: add devcontainer
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
Labels: [Status] Needs Review, [Type] Maintenance

#5365 ci: fix Dependency Review workflow
  .github/workflows/dependency-review.yml
Labels: [Type] Bug, [Status] Retro Review, [Type] Maintenance

#5379 chore: update search-dev-tools
  search/search-dev-tools/build/bundle.js
  search/search-dev-tools/package-lock.json
Labels: dependencies, [Type] Maintenance, javascript

#5380 chore: update E2E tests
  __tests__/e2e/package-lock.json
Labels: dependencies, [Type] Maintenance, [Status] No files to Deploy, javascript

#5381 ci: use exact versions of actions
  .github/actions/prepare-source/action.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/changelog-summary-prod.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/core-tests.yml
  .github/workflows/dependency-review.yml
  .github/workflows/e2e.yml
Labels: [Type] Maintenance
