Repository Automattic/vip-go-mu-plugins, pull requests merged in 2024-10, with the labels that each got.

#5901 Staging release: v20241001.1
  .github/actions/prepare-source/action.yml
  .github/workflows/changelog-summary-prod.yml
  .github/workflows/changelog-summary-staging.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/core-tests.yml
  .github/workflows/coverage-develop.yml
  .github/workflows/dependency-review.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/parsely.yml
  .github/workflows/search-dev-tools.yml
  .github/workflows/search-e2e.yml
  000-vip-init.php
  package-lock.json
  telemetry/README.md
  telemetry/class-telemetry-client.php
  telemetry/class-telemetry-event-queue.php
  telemetry/class-telemetry-event.php
  telemetry/class-telemetry-system.php
  telemetry/class-tracks.php
  telemetry/tracks/class-tracks-client.php
  telemetry/tracks/class-tracks-event-dto.php
  telemetry/tracks/class-tracks-event.php
  tests/mock-constants.php
  tests/parsely/test-mu-parsely-integration.php
  tests/telemetry/test-class-tracks-event-queue.php
  tests/telemetry/test-class-tracks.php
  tests/telemetry/tracks/test-class-tracks-client.php
  tests/telemetry/tracks/test-class-tracks-event-dto.php
  tests/telemetry/tracks/test-class-tracks-event.php
  wp-parsely.php
Labels: [Status] Needs Review

#5902 fix(two-factor): move `load_plugin_textdomain()` to `init`
  shared-plugins/two-factor/class-two-factor-core.php
Labels: [Type] Bug

#5937 Jetpack: Add shim for 13.9+ to prevent Jetpack_SSO fatal and admin notices for 13.5+
  admin-notice/admin-notice.php
  vip-jetpack/jetpack-sso-dummy.php
  vip-jetpack/vip-jetpack.php
Labels: [Component] Jetpack

#5967 WordPress Importer: Update to 0.8.3
  wordpress-importer/class-wp-import.php
  wordpress-importer/parsers.php
  wordpress-importer/parsers/class-wxr-parser-regex.php
  wordpress-importer/parsers/class-wxr-parser-simplexml.php
  wordpress-importer/parsers/class-wxr-parser-xml.php
  wordpress-importer/parsers/class-wxr-parser.php
  wordpress-importer/readme.txt
  wordpress-importer/wordpress-importer.php
Labels: [Status] Needs Review
