Repository Automattic/vip-go-mu-plugins, pull requests merged in 2025-05, with the labels that each got.

#6313 E2E: Fix timeout in login screen
  __tests__/e2e/bin/setup-env.sh
Labels: [Component] Tests

#6275 Adds stats tracking for XML RPC usage
  stats.php
  tests/test-stats.php
Labels: [Status] Needs Review

#6302 Adds log entry when user is locked out due to rate limits
  security.php
Labels: [Status] Needs Review

#6330 Remove VIP privacy policy
  001-core/privacy.php
  tests/001-core/test-privacy.php
Labels: [Status] Needs Review

#6194 Add Security Boost integration
  integrations/integration-utils.php
  integrations/remote-data-blocks.php
  integrations/security-boost.php
  tests/integrations/test-integration-utils.php
  tests/integrations/test-integration.php
  tests/integrations/test-remote-data-blocks.php
  tests/integrations/test-vip-security-boost.php
  vip-integrations.php
Labels: [Status] Needs Review

#5554 fix(files): memory usage in `filter_wp_read_image_metadata()`
  files/class-api-client.php
  files/class-vip-filesystem.php
  tests/files/test-api-client.php
Labels: [Type] Bug
