Repository Automattic/vip-go-mu-plugins, pull requests merged in 2025-04, with the labels that each got.

#4964 CANTINA-913: Match protocol in CORS header
  001-core.php
  tests/test-core-filters.php
Labels: [Status] Keep

#6260 Add and set wp-parsely 3.18 as the default version
  wp-parsely.php
Labels: [Component] Parse.ly

#6268 WP-CLI: in case there are no replicas available we should fallback to primary.
  lib/helpers/wp-cli-db/class-config.php
Labels: [Status] Needs Review
